---
title: "Assumptions and decision log guide"
format:
  html:
    embed-resources: true
---

# Introduction

Analysis **always** involves assumptions, risks and issues and decisions. It always has limitations, which might mean that it is not fit for purpose for every use case.

Keeping a formal record of important information about the analysis (such as the uncertainty involved in the analysis) and bringing this together in one place means that everybody involved in the work can find key information quickly and understand how it might affect the overall analysis or the part they are working on. 

This really matters, because assumptions, decisions and risks underpin fitness for purpose. They also change. They might become obsolete, or be replaced or adapted as you understand more. A log that brings all this together in one place will really help you to manage your analysis openly and transparently across everybody who works on the analysis. It helps everybody to have a clear, shared understanding of what is being done and why. It also makes it much easier to audit and assure your work, explain it to others, and to provide assurance that the analysis is fit for purpose. 

This really matters, because assumptions, decisions and limitations underpin fitness for purpose. They also change. They might become obsolete, or be replaced or adapted as you understand more. A log that brings all this together in one place will really help you to manage your analysis openly and transparently across everybody who works on the analysis. It helps everybody to have a clear, shared understanding of what is being done and why. It also makes it much easier to audit and assure your work, explain it to others, and to provide assurance that the analysis is fit for purpose. 

We have developed an [assumptions and decisions log template](https://best-practice-and-impact.github.io/analysis_project_documentation/assumptions_and_decisions_log_template.xlsx) for you to download. It provides the basis for recording your assumptions, decisions and limitations (identified as risks and issues). The template includes multiple worksheets to record full project information.
 
# How to use the template

The template is colour coded.   

* Blue tabs provide guidance that support the documentation tabs, or contain metadata about the template.    
* Green tabs are individual templates for pieces of quality assurance documentation.

The template includes some example entries including fictitious names, risks and assumptions. Remove these when using the template for your own projects.

## Guide to worksheets

| **Sheet Name** | **Summary** | **Details** |
|----------------|-------------|-------------|
| **README**      | Version history and other information about the template | |
| **How to Use**      | General guidance about how to use the template | |
| **Analysis Overview** | Basic details about the analysis and key responsibilities. This page should be filled out by the team which is responsible for the analysis. | The project name given here will cascade throughout the spreadsheet |
| **Documentation Links**      | Links to important documents that are not part of this QA template. This page should be filled out by the team which is responsible for the analysis. ||
| **Process Map**      | A diagram or document that sets out the end to end process for the work, including inputs, intermediate steps, outputs and upstream and downstream dependencies. | We would expect to see a URL link to the process map and any supporting documentation on this page. |
| **Roles and responsibilities** | Use this tab to record when somebody took on a governance role and accepted the responsibiltiies of the role. The template also records past governance owners so that handovers are recorded. | Guidance about what each assurance role involves and templates to record agreement to carry out that role are on the sheet labelled 'Role Details' |
| **Role Details** | Guidance about specific AQUA Book QA roles and responsibilities and how they contribute to quality assurance. Used with the Roles and Responsibilities tab. | [AQuA Book Roles](https://www.gov.uk/guidance/the-aqua-book#roles) |
| **QA Log** | The QA log sets out QA checks made during the work, their outcomes and impact. The log is a living document, maintained and reviewed throughout the lifetime of the project.    
The QA log tab provides a table which allows team and the Assurer to document planned Quality Assurance and confirm when it is completed. It also has space for a short summary of any issues Quality Assurance raises.    QA outcomes that feed into project risks and issues should be described in the decisions and issues logs together with mitigation plans when appropriate. | |
| **Decision Log** | Decisions are made during project scoping, development, setup, running and reporting.    
As issues and risks arise in development they can also lead to new decisions.  For example, there may be concerns about the validity of one of the inputs used. This might lead to a decision by the individuals in senior governance positions about how that input should be used, based on evidence about the quality of the input data. That decision is then recorded in the Decision Log.    
Often decisions can result in updates to project assumptions or new assumptions, which are then stored in the assumptions log. | |
| **Risks and Issues Log** | A log of risks and issues associated with the work and how they are scored and managed. The log is a living document, and must be maintained and reviewed throughout the lifetime of the project.     
Issues and risks can come from QA, or be raised from within the team or by stakeholders. Risks and issues that are logged on the corporate risk tool can just be linked here, there is no need to enter the details of these again. | [Risk Management at ONS](https://intranet.ons.statistics.gov.uk/task/risk-management/) |
| **Assumptions Log** | A log of important assumptions made by the work. The log should record when the assumptions were made, who made them, what they are and how they affect the work.    
The log is a living document, maintained and reviewed throughout the lifetime of the project.    
Wherever possible, assumptions should have a numerical value and an uncertainty range around the value. You should also give your assumptions a quality RAG rating and a sensitivity rating to give a sense of how important they are likely to be for the successful outcome of the analysis and how reliable you assess them to be. | |
| **Quality and Impact Guide for Assumptions** | An at-a-glance guide to how to rate the quality and impact of your assumptions. Used with the Assumptions Log tab.    If you are not sure about the quality or impact score of an assumption, err on the side of caution and go for lower quality and / or higher impact. | |
| **Ethics Assessment** | Ethical issues relating to the analysis are documented in an ethics self assessment. This should be linked to this tab. | [UK Statistics Authority Ethics Self Assessment Tool](https://uksa.statisticsauthority.gov.uk/the-authority-board/committees/national-statisticians-advisory-committees-and-panels/national-statisticians-data-ethics-advisory-committee/ethics-self-assessment-tool/) |

# Storing and maintaining the QA log

Quality assurance logs should be stored in a location accessible to everybody in the team. They are living documents and should be regularly reviewed and updated. This works best when you store the log somewhere central, where every member of the team has access.    

Where possible, store your QA logs in a place that is visible to and readable by your wider organisation, not just your own team.

If your work is written in code, we recommend storing the log alongside the code base for the work in a Git repository as part of the Git project documentation. This is good practice because if you manage changes to the log using Git version control changes to the log will be stored automatically in the Git commit log, giving you a full audit trail, and there will only ever be one "version" of the log at any time. If this is not feasible, we recommend storing the log on a Sharepoint site that is accessible to everybody in the project.