---
title: "How to use ONS Quality Questions"
format:
  html:
    embed-resources: true
---

::: {.callout-note collapse="false"}
This guidance is an ALPHA draft. It is in development and we are still working to ensure that it meets user needs.

Please get in touch with feedback to support the guidance by creating a [GitHub Issue](https://github.com/best-practice-and-impact/analysis_project_documentation/issues) or [emailing us](mailto:ASAP@ons.gov.uk).
:::

## Structure of the ONS Quality Questions

There are 61 quality questions in total. They cover all the stages of the analytical cycle. 

Answering 61 questions must seem quite daunting at first! The questions are designed to help you as you work your way through the analytical process, rather than to be answered all at once. Creating a log of answers as you move through the stages of the analysis workflow will help you to check that your work meets analytical standards, follows good practice and (if relevant) complies with the Code of Practice for Statistics. 

Answering the questions will also help you make sure that everybody working on the analysis has a clear understanding of how and why it works as it does, and to support your users when writing your outputs. Moreover, most of the answers will help you to produce the critical documents that mitigate risk like an assumptions log, decisions log, issues log, and technical guides for your team and your users. 

The AQuA book divides the analytical cycle into four stages:  

1) Scoping  
2) Design  
3) Conducting and checking analysis  
4) Delivery   

You can find the questions in the [ONS Quality Questions](https://best-practice-and-impact.github.io/analysis_project_documentation/quality_questions.html) section of the website. The questions have tabs which relate to three themes:

<details>
  <summary>Theme1: ONS Quality Questions and why they matter</summary>

Alongside each question we explain why it matters and explain the potential risks and benefits around it. We try to address the very sensible question of "why should I care about this?". 


</details>

<details>
  <summary>Theme 2: The questions and the Code of Practice for Statistics</summary>

Each question is linked with the Code of Practice for Statistics pillars of [Trustworthiness](https://code.statisticsauthority.gov.uk/the-code/trustworthiness/), [Quality](https://code.statisticsauthority.gov.uk/the-code/quality/) and [Value](https://code.statisticsauthority.gov.uk/the-code/value/). We explain the importance and relevance of each question in light of the three pillars so teams can better understand and apply these principles through out the project life cycle. 

Even if your work does not directly feed into the production of official statistics, compliance with the principles and practices of the Code is a good way to strengthen the resilience of your work, increase transparency and clarity and reduce risk.
</details>

<details>
  <summary>Theme 3: Linking the questions to AQuA roles</summary>


Quality questions are also linked to which responsible role from the [AQuA book](https://www.gov.uk/government/publications/the-aqua-book-guidance-on-producing-quality-analysis-for-government) would usually answer them. The idea is to highlight the clear line of accountability set out in the AQuA book in an easy-to-understand manner. We want to make it easier for teams to decide how the three key assurance roles of commissioner, senior responsible owner (and their analysis team) and analytical assurer are covered in their own workflows.  

The AQuA book sets out four roles that cover different areas of assurance responsibility. Taken together, they provide a comprehensive set of assurance for an analytical project. The roles are:    

* Commissioner    
* Senior Responsible Owner (SRO)    
* Analyst    
* Analytical assurer     

Let's look at the roles more detail.

**Responsibilities of the Commissioner**    
The commissioner is focused on making sure the analysis meets the required user needs.       
* Ensures that context around the work is understood so quality assurance is appropriate and proportionate.    
* Ensures that there is enough time and resource for required assurance and account for risk.    
* Must understand strengths and limitations including uncertainty so results are interpreted correctly.      
* Delivers QUALITY OF OUTCOME ("The analysis meets user needs and we understand its limitations").    

**Responsibilities of the Senior Responsible Owner**    
The Senior Responsible Owner (SRO) is accountable for the analytical workflow throughout its lifecycle. The Senior Responsible Owner is usually a senior member of the analytical team, and works closely with (or manages) the analyst team. 

There is no minimum grade for the SRO role, but they should have the expertise, resources and accountability to ensure that the analysis is well designed, complies with relevant standards, works as intended and is fit for purpose.    
* Signs off all important decisions made about the analysis to ensure that it is fit-for-purpose, prior to use.    
* Delivers QUALITY OF CONTENT ("The analysis is well-designed and uses the right tools and methods to meet user needs") alongside the analyst team.    

**Responsibilities of the Analyst**    
The analyst team usually work to the SRO. Analysts are responsible for setting up, running, checking and reporting on the analysis.    
* Assist the Commissioner and SRO in framing the question to ensure the right analysis is done.    
* Manage external specialists.    
* Design, build, document and run the analysis.      
* Delivers QUALITY OF CONTENT ("The analysis is well-designed and uses the right tools and methods to meet user needs") alongside the SRO.    

**Responsibilities of the Analytical Assurer**    
The analytical assurer is there to make sure that the analysis has the right level of assurance and that the assurance takes place.   
* Ensures that the evidence is there to demonstrate that appropriate quality assurance has happened and that uncertainty is communicated appropriately.   
* Advises the Commissioner on whether appropriate QA has happened and about any outstanding risks.    
* Involved throughout from design through to use.    
* Delivers QUALITY OF PROCESS ("The analysis does what it is supposed to do and we can prove it").    

You can read more about the four roles in the [AQuA Book](https://www.gov.uk/government/publications/the-aqua-book-guidance-on-producing-quality-analysis-for-government) and [Verification and Validation for the AQuA Book](https://www.gov.uk/government/publications/verification-and-validation-for-the-aqua-book).

</details>

## Answering the ONS Quality Questions

We have made templates for you to download and use to record your answers to the questions, as well as key project information. There is an [Excel template](https://best-practice-and-impact.github.io/analysis_project_documentation/quality_questions_excel_template.xlsx) and an [editable HTML](https://best-practice-and-impact.github.io/analysis_project_documentation/quality_questions_html_template.html) template.

Save the template in your project repository or on Sharepoint so that changes can be tracked through version control. You can update it as your analytical work progresses. 

We encourage the commissioner, analyst team and assurer to contribute response to all the questions that are relevant to their responsibilities.
To keep the level of assurance proportionate to your analysis it might be decided that only a subset of questions need be covered.

::: {.callout-note collapse="true"}

## Is there any help in deciding which questions should be covered?

The commissioner and lead analyst should agree the level of assurance required and identify which questions are most appropriate together with any possible additional ones.

The Excel template has mapped the questions to various categories including Analysis Function’s Quality Questions and Red Flags and the OSR’s Statistical Thinking – both these publications promote their questions as a core set that anyone doing analysis should consider. To identify these questions it is only necessary to filter on the appropriate columns in the worksheet.

It is also possible to filter questions relevant for each stage of the Generic Statistical Business Process Model. Many questions are relevant for more than GSBPM stage and only need be answered once!  

We aim to add further categories to subset questions best suitable for production, research and adhoc projects. These would only be suggestive but could provide a start. 
:::

For audit purposes, remember to sign and date your responses.

When analysis is due to complete the lead analyst or their designated representative should provide sign-off for the whole template if satisfied that responses provide sufficient assurance of the analysis.

