---
title: "Quality Questions Introduction"
format:
  html:
    embed-resources: true
---

::: {.callout-note collapse="false"}
This guidance is an ALPHA draft. It is in development and we are still working to ensure that it meets user needs.

Please get in touch with feedback to support the guidance by creating a [GitHub Issue](https://github.com/best-practice-and-impact/analysis_project_documentation/issues) or [emailing us](mailto:ASAP@ons.gov.uk).
:::

## Aims

This guidance provides a set of questions to help analytical and statistical teams evaluate the quality of their analysis throughout the production cycle.

The guidance is here to support teams in meeting the Office for National Statistics's (ONS) strategic objectives for improving statistical quality. You can find more information about our strategic objectives on statistical quality in the [ONS Statistical Quality Improvement Strategy](https://www.ons.gov.uk/methodology/methodologytopicsandstatisticalconcepts/qualityinofficialstatistics/onsstatisticalqualityimprovementstrategy). ONS manages quality through a [strategic risk approach](https://officenationalstatistics.sharepoint.com/sites/onswiki/SitePages/ONS_quality_management.aspx?csf=1&web=1&e=xyAJcG&cid=3da18120-8bb7-4e1f-ad34-e2793e555231).

The guidance has five main aims:  

1. To help analysts understand the level of risk they are carrying in their analytical workflows. 
2. To ensure there is a consistent end-to-end QA approach across ONS.  
3. To make it easier to comply with good practice guidance and standards including the [ONS Quality Practices](https://officenationalstatistics.sharepoint.com/sites/onswiki/SitePages/Quality-Principles.aspx?csf=1&web=1&e=FB4Q14&cid=3cc849ba-f68b-4fc2-af5c-935b82703414), [ONS Quality Standard for Analysis](https://officenationalstatistics.sharepoint.com/sites/onswiki/SitePages/Quality_Standards.aspx), the government [AQUA Book](https://www.gov.uk/government/publications/the-aqua-book-guidance-on-producing-quality-analysis-for-government) and the [Code of Practice for Statistics](https://code.statisticsauthority.gov.uk/), the [Analysis Function](https://analysisfunction.civilservice.gov.uk/) [Functional Standard for Analysis](https://www.gov.uk/government/publications/government-analysis-functional-standard--2) and the [Government Service Manual](https://www.gov.uk/service-manual/user-research/start-by-learning-user-needs) which explains how to research, document and validate user needs.  
4. To ensure there is a consistent understanding of roles and responsibilities when producing high quality analysis and statistics.  
5. To make it easier to create critical project documentation including an [assumptions and decisions log](assumptions_and_decision_log_template.xlsx), issue and decisions log, risk register and divisional [Quality Improvement Plan](https://officenationalstatistics.sharepoint.com/sites/onswiki/SitePages/Managing_Quality_Mechanisms.aspx).  

Reflecting on the questions asked in the template will help you to manage your analysis risks:

1. You will be able to document the mitigation that is in place or planned.    
2. You will know which issues and risks the project is prepared to accept and why.    
3. You can identify potential quality issues and decide how to manage and prioritise them.    
4. Having this information in once place provides a sound basis for regular reviews of assumptions, issues and risks associated with the workflow, in line with recommended good practice.    

## How the questions draw on other frameworks

The [AQuA book](https://www.gov.uk/government/publications/the-aqua-book-guidance-on-producing-quality-analysis-for-government) sets out a standard framework for managing analytical quality in HM Government. The AQuA framework is there to make sure that our work can be trusted to inform good decision making, while the [Code of Practice for Statistics](https://code.statisticsauthority.gov.uk/) sets out the principles and practices that producers of official statistics should commit to.    

Two other pieces of guidance have motivated us to produce this template. One is the [Analysis Function guidance on Quality Questions and Red Flags](https://analysisfunction.civilservice.gov.uk/policy-store/quality-questions-and-red-flags/#:~:text=The%20%27Quality%20Questions%20and%20Red,for%20National%20Statistics%20). The other is the Office for Statistics Regulation (OSR) guidance on [Thinking about quality when producing statistics](https://osr.statisticsauthority.gov.uk/publication/regulatory-guidance-thinking-about-quality-when-producing-statistics/). Both of these provide sets of questions that analysts can use to interrogate their work and assure its quality. 

Building on these resources, this guidance sets out quality questions that are relevant for each stage of analytical cycle. The quality questions are at their most effective if they are asked at the right stage. Once that stage is passed, experience suggests that it is normally difficult to go back and address the points the questions ask by retrofitting at a later stage of the analysis.  

Each question is linked with the Code of Practice for Statistics pillars of [Trustworthiness](https://code.statisticsauthority.gov.uk/the-code/trustworthiness/), [Quality](https://code.statisticsauthority.gov.uk/the-code/quality/) and [Value](https://code.statisticsauthority.gov.uk/the-code/value/). We explain the importance and relevance of each question in light of the three pillars so teams can better understand and apply these principles through out the project life cycle.  

Quality questions are also linked to which responsible role from the AQuA book would usually answer them. The idea is to highlight the clear line of accountability set out in the AQuA book in an easy-to-understand manner. We want to make it easier for teams to decide how the three key assurance roles of commissioner, senior responsible owner (and their analysis team) and analytical assurer are covered in their own workflows.  

## Structure of the guidance

There are 61 quality questions in total. They cover all the stages of the analytical cycle. 

Answering 61 questions probably seems like a daunting task at first! The questions are designed to help you as you work your way through the analytical process, rather than to be answered all at once. Creating a log of answers as you move through the stages of the analysis workflow will help you to check that your work meets analytical standards, follows good practice and (if relevant) complies with the Code of Practice for Statistics. 

Answering the questions will also help you make sure that everybody working on the analysis has a clear understanding of how and why it works as it does, and to support your users when writing your outputs. Moreover, most of the answers will help you to produce the critical documents that mitigate risk like an assumptions log, decisions log, issues log, and technical guides for your team and your users. 

The AQuA book divides the analytical cycle into four stages:  

1) Scoping  
2) Design  
3) Conducting and checking analysis  
4) Delivery   

You can find the questions in the [Quality Questions](https://best-practice-and-impact.github.io/analysis_project_documentation/quality_questions.html) section of the website, which is divided across three themes:

### a) Quality Questions and why they matter

This tab lists the quality questions that are relevant for each stage of analytical cycle. Alongside each question we explain why it matters and explain the potential risks and benefits around it. We try to address the very sensible question of "why should I care about this?". 

We encourage commissioner, analyst team and analytical assurer to answer all the questions that are relevant to their responsibilities. We have made a [downloadable, editable HTML template](https://best-practice-and-impact.github.io/analysis_project_documentation/quality_questions_html_template.html) that you can use to record your answers to the questions, as well as key project information. Once you have recorded answers, save the HTML file in your project archive. You can update it as you work through the questions.

User needs and project aims often change as things evolve, so the HTML template allows you to edit answers by simply changing the text in the editable text boxes. To track these changes, the person writing the answer should include their full-name, the date they have added the answer, and the date the next review is due. 

The Senior Responsible Owner (SRO) is the lead analyst responsible for the workflow (or relevant part of it). The SRO or their designated representative needs to sign-off all the answers at the top of the sheet. 

It is best to complete and save the log of answers for each stage of analytical cycle. Answers can be saved by pressing Ctrl + S. To undo an action press Ctrl + Z. Pressing Ctrl + S will let you save a copy of the HTML template on your device. 

### b) The questions and the Code of Practice for Statistics

This tab shows the pillars and principles of Code of Practice for Statistics each quality question relates to. The text in this column is copied from Code of Practice for Statistics. Even if your work does not directly feed into the production of official statistics, compliance with the principles and practices of the Code is a good way to strengthen the resilience of your work, increase transparency and clarity and reduce risk.

### c) Linking the questions to AQuA roles

This tab explains the responsibilities required to deliver analysis that is fit-for-purpose. The roles and responsibilities in this tab are reproduced from the AQuA book. The tab links the quality questions with the relevant AQuA Book responsibilities at each stage of analytical cycle.  

The AQuA book sets out four roles that cover different areas of assurance responsibility. Taken together, they provide a comprehensive set of assurance for an analytical project. The roles are:    

* Commissioner    
* Senior Responsible Owner (SRO)    
* Analyst    
* Analytical assurer     

Let's look at the roles more detail.

**Responsibilities of the Commissioner**    
The commissioner is focused on making sure the analysis meets the required user needs.       
* Ensures that context around the work is understood so quality assurance is appropriate and proportionate.    
* Ensures that there is enough time and resource for required assurance and account for risk.    
* Must understand strengths and limitations including uncertainty so results are interpreted correctly.      
* Delivers QUALITY OF OUTCOME ("The analysis meets user needs and we understand its limitations").    

**Responsibilities of the Senior Responsible Owner**    
The Senior Responsible Owner (SRO) is accountable for the analytical workflow throughout its lifecycle. The Senior Responsible Owner is usually a senior member of the analytical team, and works closely with (or manages) the analyst team. 

There is no minimum grade for the SRO role, but they should have the expertise, resources and accountability to ensure that the analysis is well designed, complies with relevant standards, works as intended and is fit for purpose.    
* Signs off all important decisions made about the analysis to ensure that it is fit-for-purpose, prior to use.    
* Delivers QUALITY OF CONTENT ("The analysis is well-designed and uses the right tools and methods to meet user needs") alongside the analyst team.    

**Responsibilities of the Analyst**    
The analyst team usually work to the SRO. Analysts are responsible for setting up, running, checking and reporting on the analysis.    
* Assist the Commissioner and SRO in framing the question to ensure the right analysis is done.    
* Manage external specialists.    
* Design, build, document and run the analysis.      
* Delivers QUALITY OF CONTENT ("The analysis is well-designed and uses the right tools and methods to meet user needs") alongside the SRO.    

**Responsibilities of the Analytical Assurer**    
The analytical assurer is there to make sure that the analysis has the right level of assurance and that the assurance takes place.   
* Ensures that the evidence is there to demonstrate that appropriate quality assurance has happened and that uncertainty is communicated appropriately.   
* Advises the Commissioner on whether appropriate QA has happened and about any outstanding risks.    
* Involved throughout from design through to use.    
* Delivers QUALITY OF PROCESS ("The analysis does what it is supposed to do and we can prove it").    

You can read more about the four roles in the [AQuA Book](https://www.gov.uk/government/publications/the-aqua-book-guidance-on-producing-quality-analysis-for-government) and [Verification and Validation for the AQuA Book](https://www.gov.uk/government/publications/verification-and-validation-for-the-aqua-book).
