# Issues log

The issues log provides a standard template to record all the issues incurred during the analysis lifecycle. Without documentation, risks and issues may be well understood by one part of the team and totally unknown by others.  It is therefore important to maintain an issues log to ensure that everybody knows about the issues that the analysis includes. The register helps teams to store problems and challenges that arise during analysis development for future review and mitigation. It aims to make the system of analysis development more efficient and more effective and prevent the retreading of old ground.

## Definitions

Start filling in the template by inserting the full name of the analysis (this should align with the name given on the analysis publications or output report) and financial year of interest.

**Issue ID:** Give each issue a unique ID so that it can be tracked easily and cross referenced.    
**Issue:** Enter a name for the issue. It could be anything raised by the team, anything raised during quality assurance by the team members or external reviewers. Include the location of the issue, for example, line number of code, error in publication, where it arises in the workflow, resource constraint.    
**Date first identified:** Enter the date the issue was first identified.    
**Plain English description of issue:** A brief summary of the underlying cause and nature of issue in plain English explaining what is creating problem.    
**Impact of issue:** Brief summary of what is being impacted, for example, timeline, accuracy, cost of project.    
**Status of issue:** From the dropdown menu, select ‘Resolved’ if the issue has been resolved or ‘Shelved’ if the issue has yet to be handled.    
**Justification of status:** Brief summary of how the proposed solution has helped in overcoming the issue if the status is ‘Resolved’. For ‘Shelved’ issues, explain why it is decided to deal with later.     
**Proof of resolution:** Write the name of the output report/methodology paper or the published document which the issue relates to and how the resolution has impacted it. If the issue was related to code, identify the location of revision made within the code by mentioning the line number.    
**Date of last review/update:** Enter the date the issue was reviewed/updated.    
**Reviewed by:** Enter the full name of individual(s) within the analysis team who have reviewed the decision made to resolve or shelve the issue.    
**Next review/update due on:** Enter the date the issue needs to be reviewed or updated in future.    
