::: {.callout-note collapse="false"}
This guidance is an ALPHA draft. It is in development and we are still working to ensure that it meets user needs.

Please get in touch with feedback to support the guidance by creating a [GitHub Issue](https://github.com/best-practice-and-impact/analysis_project_documentation/issues) or [emailing us](mailto:ASAP@ons.gov.uk).
:::

# Assumptions Log

Published: 15 March 2023

This log contains a list of assumptions used in this analysis. It also provides RAG status assessments for each assumption.

## Definitions

Assumptions are ranked red, amber or green (a RAG score) depending on quality. The quality of an assumption measures both how certain and robust an assumption is and how appropriate it is for its intended use. 

For example, we would usually consider a well documented assumption drawn from published evidence to be very robust, but if it needs to be transformed or adapted significantly to fit the analysis, the quality rating would probably need downgrading. You would normally lower the quality rating if it is not possible to get technical sign-off for the assumption (e.g. because of lack of technical knowledge). You will also want to lower the quality if the confidence interval is likely to be wide (i.e. you wouldn’t be surprised if the value was 50% different from what you measure because of uncertainty).

| **RAG Rating** | **Assumption quality** |
|------------|--------------------|
| **GREEN**      | Based on validated "actual" data; Methodology is robust; No or few transformations, or transformation methodology is fully verified and robust; Data is current and signed off by experts; Confidence intervals are narrow. |
| **AMBER**      | The methodology is robust but based on limited data; Data required significant transformation to fit the model; Confidence interval is quite wide; Data has not been reviewed recently. |
| **RED**        | Unclear/unreliable data source or no data source provided; Based on limited data and methodology not robust; Data is not current; Confidence interval is wide or quality is unknown. |

: {tbl-colwidths="[25,75]"}

## Assumptions - UK universities input dataset

This analysis makes the following assumptions

| **Assumption Number** | **Assumption description** | **Quality Rating** |
|-------------------|------------------------|---------|
| 1 | Data is representative of the population | GREEN |
| 2 | Data does not exclude any population groups based on their demographic and socio-economic characteristics | GREEN |
| 3 | All UK universities report data to the Higher Education Statistics Agency (HESA) | RED |
| 4 | All universities accurately report the number of students enrolled during the academic year | RED |
| 5 | All universities accurately report the number of students who dropped out during the academic year | RED |
| 6 | The academic year is consistently measured across UK universities | RED |
| 7 | Students who receive special education services are excluded from the calculation of dropout rates | RED |
| 8 | There is complete information for all the variables in the analysis | RED |
| 9 | The data collection process has not changed at all over time | RED |

: {tbl-colwidths="[10,70,20]"}
