---
title: ""
format:
  html:
    embed-resources: true
---

## Aims

This guidance provides a set of questions to help analytical and statistical teams evaluate the quality of their analysis throughout the production cycle. The guidance is here to support teams in meeting the Office for National Statistics's (ONS) strategic objectives for improving statistical quality. You can find more information about our strategic objectives on statistical quality in the [ONS Statistical Quality Improvement Strategy](https://www.ons.gov.uk/methodology/methodologytopicsandstatisticalconcepts/qualityinofficialstatistics/onsstatisticalqualityimprovementstrategy). ONS manages quality through a [strategic risk approach](https://officenationalstatistics.sharepoint.com/sites/onswiki/SitePages/ONS_quality_management.aspx?csf=1&web=1&e=xyAJcG&cid=3da18120-8bb7-4e1f-ad34-e2793e555231).

The aim of this guidance is:  

1. To help teams understand the level of risk they are carrying in their analytical workflows. Reflecting on the points raised in this template, documenting what mitigation is planned or in place or that your project is accepting the risk and why will enable you to identify potential quality issues and decide how to prioritise them. It also provides a sound basis for regular reviews of the risks associated with the workflow, in line with recommended good practice.
2. To ensure there is a consistent end-to-end QA approach across divisions and teams in ONS.  
3. To make it easier to comply with good practice guidance and standards including the [ONS Quality Practices](https://officenationalstatistics.sharepoint.com/sites/onswiki/SitePages/Quality-Principles.aspx?csf=1&web=1&e=FB4Q14&cid=3cc849ba-f68b-4fc2-af5c-935b82703414), [ONS Quality Standard for Analysis](https://officenationalstatistics.sharepoint.com/sites/onswiki/SitePages/Quality_Standards.aspx), the government [AQUA Book](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/416478/aqua_book_final_web.pdf) and the [Code of Practice for Statistics](https://code.statisticsauthority.gov.uk/), the [Analysis Function](https://analysisfunction.civilservice.gov.uk/)'s [Functional Standard for Analysis](https://www.gov.uk/government/publications/government-analysis-functional-standard--2) and the [Service Manual](https://www.gov.uk/service-manual/user-research/start-by-learning-user-needs) which explains how to research, document and validate user needs.  
4. To ensure there is a consistent understanding of roles and responsibilities when producing high quality analysis and statistics.  
5. To make it easier to create critical project documentation including an [assumptions and decisions log](https://officenationalstatistics.sharepoint.com/:x:/r/sites/anstanpi/Modelling_Best_Practice/Resources/quality_assurance_templates/assumptions_and_decision_log_template.xlsx?d=wdfc9cdc643584edca8317e49aff8e67b&csf=1&web=1&e=4MSSwy), a risk and issue register and divisional [Quality Improvement Plan](https://officenationalstatistics.sharepoint.com/sites/onswiki/SitePages/Managing_Quality_Mechanisms.aspx).  


The AQuA book sets out a standard framework for managing analytical quality in government. helps to make sure that our work can be trusted to inform good decision making, while the Code of Practice for Statistics sets out the principles and practices that producers of official statistics should commit to. Two other pieces of guidance have motivated us to produce this template. One is the [Analysis Function guidance on Quality Questions and Red Flags](https://analysisfunction.civilservice.gov.uk/policy-store/quality-questions-and-red-flags/#:~:text=The%20%27Quality%20Questions%20and%20Red,for%20National%20Statistics%20). The other is the Office for Statistics Regulation (OSR) guidance on [Thinking about quality when producing statistics](https://osr.statisticsauthority.gov.uk/publication/regulatory-guidance-thinking-about-quality-when-producing-statistics/). Both of these provide sets of questions that analysts can use to interrogate their work and assure its quality. 

Building on these cross-government resources, this guidance sets out quality questions that are relevant for each stage of analytical cycle. The quality questions are at their most effective if they are asked at the right stage. Once that stage is passed, experience suggests that it is normally difficult to go back and address the points the questions ask through retrofitting at a later stage of the analysis.  

Each question is linked with the Code of Practice for Statistics pillars of [Trustworthiness](https://code.statisticsauthority.gov.uk/the-code/trustworthiness/), [Quality](https://code.statisticsauthority.gov.uk/the-code/quality/) and [Value](https://code.statisticsauthority.gov.uk/the-code/value/). We explain the importance and relevance of each question in light of the three pillars so teams can better understand and apply these principles through out the project life cycle.  

Quality questions are also categorised by the responsible individuals required to answer them. The idea is to highlight a clear line of accountability set out in the Aqua book in an easy-to-understand manner. We want to make it easier for teams to see how the three key Aqua roles of commissioner, analytical lead (and their team) and analytical assurer are covered in their own workflows.  

## Structure of the guidance

There are 60 questions in total. They cover all the stages of the analytical cycle. Answering 60 questions may seem a daunting task at first but the questions are designed to help you throughout the analytical process. Creating a log of answers as you move through the stages of the workflow will later help you to ensuring your work meets analytical standards, follows good practice and complies with the Code of Practice for Statistics. It will also help you make sure that everybody working on the analysis has a clear understanding of how and why it works as it does, and to support your users when writing your outputs. Moreover, most of the answers will help you to producing other critical documents like an assumptions log, decision log, issues log, and technical guides for your team and for your users. 

The Aqua book divides the stages of the analytical cycle into:  

1) Scoping  
2) Design  
3) Conducting and checking analysis  
4) Delivery   

Each stage is covered by the following tabs in the HTML document:

### a) Quality Questions 

This tab lists the quality questions that are relevant for each stage of analytical cycle. It provides space in the form of editable text boxes (with no word limit) to write the answers. We encourage commissioner, analyst team and analytical assurer to answer all the questions given their responsibilities.

User needs or project aims often change over time, so the template allows you to edit answers by simply changing the text in the editable text boxes. To track these changes, the person writing the answer should include their full-name, the date they have added the answer, and the date the next review is due. 

The Senior responsible owner (SRO) is the lead analyst responsible for the workflow (or relevant part of it). The SRO needs to sign-off all the answers. It is best to complete and save the log of answers for each stage of analytical cycle. Answers can be saved by pressing Ctrl+S. To undo a action press Ctrl+Z. Pressing Ctrl+S will automatically download a copy of the HTML page on your machine. 

### b) Importance

This tab explains why understanding each quality question matters and explains the potential risks and benefits around it. It tries to address the valid question of "why should I care about this?".

### c) Code of Practice for Statistics

This tab shows the pillars and principles of Code of Practice for Statistics each quality question relates to. The text in this column is copied from Code of Practice for Statistics. Even if your work does not directly feed into the production of official statistics, compliance with the principles and practices of the Code is a good way to strengthen the resilience of your work, increase transparency and clarity and reduce risk.

### d) Aqua roles  and responsibilities

This tab explains the responsibilities required to deliver analysis that is fit-for-purpose. The roles and responsibilities in this tab are copied as is from AQUA book. The tab links the quality questions with the relevant responsibilities at each stage of analytical cycle.  

The Aqua book recommends the creation of four identifiable roles to cover different areas of responsibility- SRO, commissioner, analyst and analytical assurer. 

**Responsibilities of SRO**  
- A Single Responsible Owner for each analytical workflow throughout its lifecycle. The SRO is often a senior member of the analytical team or a divisional director or other senior leader.
- Signs off all important decisions made about the analysis to ensure that it is fit-for-purpose, prior to use.

**Responsibilities of Commissioner**  
- Ensures that context is understood so quality assurance is appropriate and proportionate.  
- Ensures that there is enough time and resource for required assurance and account for risk.  
- Must understand strengths and limitations including uncertainty so results are interpreted correctly.  
- Delivers QUALITY OF OUTCOME ("The analysis meets user needs and we understand its limitations").

**Responsibilities of Analyst**  
- Assist the Commissioner in framing the question to ensure the right analysis is done.  
- Manage external specialists.  
- Design, build, document and run the analysis.  
- Delivers QUALITY OF CONTENT ("The analysis is well-designed and users the right tools and methods to meet user needs").

**Responsibilities of Analytical Assurer**  
- Ensures that the evidence is there to demonstrate that appropriate quality assurance has happened and that uncertainty is communicated appropriately.  
- Advises the Commissioner on whether appropriate QA has happened and about any outstanding risks.  
- Involved throughout from design through to use.  
- Delivers QUALITY OF PROCESS ("The analysis does what it is supposed to do and we can prove it").

