---
title: ""
format:
  html:
    embed-resources: true
---

To make the most out of this guidance, we strongly recommend that all teams identify the responsible individuals at the start of the analytical cycle. This is crucial as each of these individuals has a role in ensuring the analysis is fit-for-purpose.


<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse; 
}
</style>

<table style="width:100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse; font size="2" face="Courier New">
<TR VALIGN=TOP>
    <th style="text-align: center;"> Name of Senior Responsible Owner (SRO)</th>
    <th style="text-align: center"> Name of Commissioner</th>
    <th style="text-align: center"> Name of Analyst(s)</th>
    <th style="text-align: center"> Name of Analytical Assurer(s)</th>

</tr>
 <tr height=83 style='height:62.5pt'>
  <td> <p id="content" contenteditable>Enter name here...                         </p></td>
  <td> <p id="content" contenteditable>Enter name here...                         </p></td>
  <td> <p id="content" contenteditable>Enter name here...                         </p></td>
  <td> <p id="content" contenteditable>Enter name here...                         </p></td>

  </tr>
</table>

## I. Scoping

::: {.panel-tabset}

## Quality Questions

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<table style="width:100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse; font size="2" face="Courier New">
<TR VALIGN=TOP>
    <th> </th>
    <th style="width:50%; text-align: center;"> Quality Questions</th>
    <th style="width:50%; text-align: center;">Answers</th>
    <th style="text-align: center"> Answer added by</th>
    <th style="text-align: center"> Date answer added</th>
    <th style="text-align: center"> Is SRO satisfied with the answer?</th>
    <th style="text-align: center"> Next review due on</th>
    <th style="text-align: center"> Has anything changed from last review?</th>


</tr>
 <tr height=83 style='height:62.5pt'>
<td height=21 class=xl657005 width=31 style='height:15.5pt;width:24pt'>Q1</td>
  <td class=xl657005 width=321 style='border-left:none;width:241pt'>What
  question is the analysis trying to answer?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl657005 width=31 style='height:15.5pt;border-top:none;
  width:24pt'>Q2</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Why do we need to answer this question?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q3</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Which organisational priorities does this work address?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl657005 width=31 style='height:15.5pt;border-top:none;
  width:24pt'>Q4</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is the model business critical?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl657005 width=31 style='height:15.5pt;border-top:none;
  width:24pt'>Q5</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Who needs to know the answer?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q6</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Who do we need to consult to make sure we meet the right user
  needs?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q7</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>How will you know you have answered this question correctly?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q8</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>What is the estimated time and resource required to answer this
  question (in months)?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q9</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>What are the consequences if the work is not carried out now?</td>
  
  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q10</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>What are the consequences if the work is not carried out
  correctly?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q11</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Who is the commissioner, SRO and analytical assurer of this
  analysis?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q12</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>What tools and resources will you use during the production
  process? Are they the best for the job?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q13</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Do you have the right internal and external resources and
  capability to deliver the analysis?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q14</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>What are the anticipated risks of the analysis? Have you
  discussed this risk with the customers?<span
  style='mso-spacerun:yes'> </span></td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q15</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Have you developed a contingency plan to put in place if the
  mitigation plan fails?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q16</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Does the data and model comply with ethical requirements?<span
  style='mso-spacerun:yes'> </span></td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q17</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>What questions are outside the scope of the analysis?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl657005 width=31 style='height:15.5pt;border-top:none;
  width:24pt'>Q18</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Will internal auditing and peer review be performed?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q19</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Will external experts be involved in development and scruitny of
  analysis?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

  </tr>
</table>

## Importance 

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
<TR VALIGN=TOP>
    <th> </th>
    <th> Quality Questions</th>
    <th> Why do I need to know the answer to this?</th>

</tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6611297 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q1</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>What question is the analysis trying to answer?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>A clear understanding of the question is essential. It enables
  your team to scope out requirements, understand the strengths and limitations
  of the analysis and ensure that it is fit for purpose.<br>
    If the question is unclear you risk designing and delivering analysis which
  does not meet user needs.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl6611297 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q2</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>Why do we need to answer this question?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>Exploring and understanding the need for, purpose of and end use
  of analysis will help you to understand the importance and impact of your
  work, how it supports decision making and how others will use it. It will
  also help you to make sure that all stages of analysis are fit for purpose
  and that the final output correctly answers the question you began with.<span
  style='mso-spacerun:yes'>  </span></td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6611297 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q3</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>Which organisational priorities does this work address?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>Setting out how the work aligns with organisational priorities
  helps you to understand how the work fits with wider strategic objectives and
  how important it is to carry out the analysis now. It informs the level of
  assurance needed to make sure the work is fit for purpose.</td>
 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl6611297 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q4</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>Is the model business critical?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>Identifying if the model is business critical helps to define
  the level of assurance needed to ensure it is fit for purpose.</td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl6611297 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q5</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>Who needs to know the answer?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>If you don’t know what your outputs will be used for, you cannot
  be sure that they will meet user needs. A good understanding of likely use
  cases and how you prioritise them is an essential part of making sure that
  all parts of your analysis are fit for purpose.</td>
 </tr>
 <tr height=167 style='height:125.0pt'>
  <td height=167 class=xl6611297 width=31 style='height:125.0pt;border-top:
  none;width:24pt'>Q6</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>Who do we need to consult to make sure we meet the right user
  needs?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>Analysis must be well understood by relevant users, or else
  risks scope creep and misspecification. You should identify stakeholders and
  users who should be consulted before designing an analysis and take account
  of their views and considerations<span style='mso-spacerun:yes'> 
  </span>wherever relevant. Consulting the right stakeholders makes sure that
  your team and your users have a shared understanding and vision of what is
  the best way to approach answering the question, what the output should look
  like, how well the users understand the process, its quality and limitations,
  and what can be done to tailor the final ouput to best meet user needs.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6611297 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q7</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>How will you know you have answered this question correctly?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>Being clear about the outputs required and the level of error
  that is acceptable is essential for ensuring that the final output is
  accurate and reliable and that users and your team have a good understanding
  of limitations and uncertainty. It is also essential when designing
  verification and validation activities that will help you to check the
  robustness of results under a range of plausible assumptions about methods
  and data.</td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl6611297 width=31 style='height:100.0pt;border-top:
  none;width:24pt'>Q8</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>What is the estimated time and resource required to answer this
  question (in months)?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>Without a clear understanding of time and resource constraints,
  you may overcommit. It is important to push back against unrealistic demands
  if the team is not able to set aside sufficent time to effectively quality
  assure the analysis. The users and commissioner should fully understand and
  accept the associated risks to quality when time and resource pressures are
  unavoidable and will mean that there are unavoidable risks to quality.<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6611297 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q9</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>What are the consequences if the work is not carried out now?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>Understanding why the work needs to happen now will help you to
  prioritise and make sure that limited resources are targeted to the right
  activities.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl6611297 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q10</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>What are the consequences if the work is not carried out
  correctly?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>It is important to understand potential legal, financial or
  reputational consequences if the work is not carried out correctly so that
  you can design a proportionate set of assurance activities. The nature and
  extent of the principal risks that the organisation is willing to take in
  achieving its objectives should also determined alongside informing decision
  making.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6611297 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q11</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>Who is the commissioner, SRO and analytical assurer of this
  analysis?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>Clear lines of accountability strengthen assurance processes and
  make sure that important decisions are signed off by the right people. There
  should be a clear understanding of who is responsible for managing, producing
  and quality assuring the analysis in the team.<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6611297 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q12</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>What tools and resources will you use during the production
  process? Are they the best for the job?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>Before starting an analysis, identify all the skills and
  resources needed to produce the final output in a sustainable and
  reproducible way and to quality assure it at every step. The platform used to
  host the analysis and the software to build and run the analysis should be
  appropriate given uses and risks. For example, producing critical outputs in
  Excel does not comply with best practice and is unlikely to be robust or
  verifiable.</td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6611297 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q13</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>Do you have the right internal and external resources and
  capability to deliver the analysis?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>If the team lacks capability, sufficient resource or time, this
  increases the risk that the analysis will not be fit for purpose or
  sufficiently assured.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl6611297 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q14</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>What are the anticipated risks of the analysis? Have you
  discussed this risk with the customers?<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>You must identify potential risks and their impact well in
  advance to enable effective mitigation and quicker, confident
  decision-making. It is also important that users understand risks to ensure
  that their expectations and requirements are met. You should document how you
  have identified and are monitoring and mitigating risks.</td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl6611297 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q15</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>Have you developed a contingency plan to put in place if the
  mitigation plan fails?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>Risks that would have a high impact on the analysis but a low
  probability of occurring should still be accounted for, or else risk serious
  harm to the public. Without well designed contingencies we put the public at
  risk.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6611297 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q16</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>Does the data and model comply with ethical requirements?<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>Analysis must comply with ethics standards to ensure public
  confidence. Data ethics are an essential part of any good analysis. You
  should consider the ethical implications of the analysis and how they feed
  through to use of analysis when you create the workflow and report your
  findings.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6611297 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q17</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>What questions are outside the scope of the analysis?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>Limitations affect the workings of the analysis and the quality
  of outputs and what can be done with them. By being clear about the
  limitations of the analysis we ensure that we have mitigated or accepted
  them. Limitations must be documented so everybody using the analysis has a
  shared understanding of them.<span style='mso-spacerun:yes'>  </span></td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6611297 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q18</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>Will internal auditing and peer review be performed?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>Internal audit and peer review are critical for monitoring and
  assuring that the analysis is performed appropriately and its meeting the
  required aims and objectives. The outcomes of the peer review should be
  documented and any relevant actions and recommendations should be addressed
  and taken forward.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6611297 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q19</td>
  <td class=xl6611297 width=319 style='border-top:none;border-left:none;
  width:240pt'>Will external experts be involved in development and scruitny of
  analysis?</td>
  <td class=xl6611297 width=396 style='border-top:none;border-left:none;
  width:297pt'>Your team should commission external specialists to peer review
  or audit the analysis in proportion to the risks around the analysis and its
  use. They should be.able to draw on expertise and experience across
  government and beyond to get feedback, exchange experience and best practices
  to improve the analysis.</td>
  </tr>
</table>

## Code of Practice for Statistics

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
<TR VALIGN=TOP>
    <th> </th>
    <th> Quality Questions</th>
    <th> Which pillar and principle of Code of Practice are relevant here?  
    *Trustworthiness (T), Quality (Q), Value (V)</th>

</tr>
 <tr height=83 style='height:62.5pt'>

<td height=83 class=xl656766 width=31 style='height:62.5pt;width:24pt'>Q1</td>
  <td class=xl656766 width=321 style='border-left:none;width:241pt'>What
  question is the analysis trying to answer?</td>
  <td class=xl656766 width=368 style='border-left:none;width:276pt'>V1.1
  Statistics producers should maintain and refresh their understanding of the
  use and potential use of the statistics and data. They should consider the
  ways in which the statistics might be used and the nature of the decisions
  that are or could be informed by them.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl656766 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q2</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>Why do we need to answer this question?</td>
  <td class=xl656766 width=368 style='border-top:none;border-left:none;
  width:276pt'>V1.1 Statistics producers should maintain and refresh their
  understanding of the use and potential use of the statistics and data. They
  should consider the ways in which the statistics might be used and the nature
  of the decisions that are or could be informed by them.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl656766 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q3</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>Which organisational priorities does this work address?</td>
  <td class=xl656766 width=368 style='border-top:none;border-left:none;
  width:276pt'>T2.1 The Chief Statistician/Head of Profession for Statistics
  should have sole authority for deciding on methods, standards and procedures,
  and on the content and timing of the release of regular and ad hoc official
  statistics. This should include: determining the need for new official
  statistics, ceasing the release of official statistics, and the development
  of experimental statistics.</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl656766 width=31 style='height:15.5pt;border-top:none;
  width:24pt'>Q4</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is the model business critical?</td>
  <td class=xl656766 width=368 style='border-top:none;border-left:none;
  width:276pt'>&nbsp;</td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl656766 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q5</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>Who needs to know the answer?</td>
  <td class=xl676766 width=368 style='border-top:none;border-left:none;
  width:276pt'>V1 Users of statistics and data should be at the centre of
  statistical production; their needs should be understood, their views sought
  and acted upon, and their use of statistics supported.</td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl656766 width=31 style='height:100.0pt;border-top:none;
  width:24pt'>Q6</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>Who do we need to consult to make sure we meet the right user
  needs?</td>
  <td class=xl676766 width=368 style='border-top:none;border-left:none;
  width:276pt'>V1<span style='mso-spacerun:yes'>  </span>Users of statistics
  and data should be at the centre of statistical production; their needs
  should be understood, their views sought and acted upon, and their use of
  statistics supported. V1.2 Statistics producers should use appropriate ways
  to increase<span style='mso-spacerun:yes'>  </span>awareness of the
  statistics and data, communicate effectively with the widest possible
  audience, and support users and potential <br>
    users in identifying relevant statistics to meet their needs.</td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl656766 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q7</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>How will you know you have answered this question correctly?</td>
  <td class=xl676766 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q3 Producers of statistics and data should explain clearly how
  they assure themselves that statistics and data are accurate, reliable,
  coherent and timely.</td>
 </tr>
 <tr height=167 style='height:125.0pt'>
  <td height=167 class=xl656766 width=31 style='height:125.0pt;border-top:none;
  width:24pt'>Q8</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>What is the estimated time and resource required to answer this
  question (in months)?</td>
  <td class=xl686766 width=368 style='border-top:none;border-left:none;
  width:276pt'>T5 People producing statistics should be appropriately skilled,
  trained and supported in their roles and professional development. T4.3
  Sufficient human, financial and technological resources should be provided to
  deliver statistical services that serve the public good. T3.5 Statistics and
  data should be released on a timely basis and at intervals that meet the
  needs of users as far as practicable. The statistics should be released as
  soon as they are considered ready, under the guidance of the Chie Statistician/Head
  of Profession for Statistics.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl656766 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q9</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>What are the consequences if the work is not carried out now?</td>
  <td class=xl656766 width=368 style='border-top:none;border-left:none;
  width:276pt'>T2.1 The Chief Statistician/Head of Profession for Statistics
  should have sole authority for deciding on methods, standards and procedures,
  and on the content and timing of the release of regular and ad hoc official
  statistics. This should include: determining the need for new official
  statistics, ceasing the release of official statistics, and the development
  of experimental statistics.<span style='mso-spacerun:yes'>  </span></td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl656766 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q10</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>What are the consequences if the work is not carried out
  correctly?</td>
  <td class=xl676766 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q3 Producers of statistics and data should explain clearly how
  they assure themselves that statistics and data are accurate, reliable,
  coherent and timely.</td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl656766 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q11</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>Who is the commissioner, SRO and analytical assurer of this
  analysis?</td>
  <td class=xl656766 width=368 style='border-top:none;border-left:none;
  width:276pt'>T5.2 The roles and responsibilities of those involved in the
  production of statistics and data should be clearly defined with supporting
  guidance provided to help staff carry out their roles.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl656766 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q12</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>What tools and resources will you use during the production
  process? Are they the best for the job?</td>
  <td class=xl686766 width=368 style='border-top:none;border-left:none;
  width:276pt'>T5 People producing statistics should be appropriately skilled,
  trained and supported in their roles and professional development. T5.5 Staff
  should be provided with the time and resources required to develop their
  skills, knowledge and competencies. T4.3 Sufficient human, financial and
  technological resources should be provided to deliver statistical services
  that serve the public good.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl656766 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q13</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>Do you have the right internal and external resources and
  capability to deliver the analysis?</td>
  <td class=xl656766 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q3 Producers of statistics and data should explain clearly how
  they assure themselves that statistics and data are accurate, reliable,
  coherent and timely. T4.3 Sufficient human, financial and technological
  resources should be provided to deliver statistical services that serve the
  public good.</td>
 </tr>
 <tr height=233 style='height:175.0pt'>
  <td height=233 class=xl656766 width=31 style='height:175.0pt;border-top:none;
  width:24pt'>Q14</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>What are the anticipated risks of the analysis? Have you
  discussed this risk with the customers?<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl676766 width=368 style='border-top:none;border-left:none;
  width:276pt'>V1<span style='mso-spacerun:yes'>  </span>Users of statistics
  and data should be at the centre of statistical production; their needs
  should be understood, their views sought and acted upon, and their use of
  statistics supported. V4.3 Users should be involved in the ongoing
  development of statistics and data, exploring and testing statistical
  innovations, so that the statistics remain relevant and useful. Q3.2 Quality
  assurance arrangements should be proportionate to the nature of the quality
  issues and the importance of the statistics in serving the public good.
  Statistics producers should be transparent about the quality assurance
  approach taken throughout the preparation of the statistics. The risk and
  impact of quality issues on statistics and data should be minimised to an
  acceptable level for the intended uses.<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl656766 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q15</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>Have you developed a contingency plan to put in place if the
  mitigation plan fails?</td>
  <td class=xl676766 width=368 style='border-top:none;border-left:none;
  width:276pt'>T4.5 Organisations should be open about their commitment to
  quality and make clear their approach to quality management. They should
  ensure that the organisational structure and tools are in place to manage
  quality effectively, and promote and adopt appropriate quality standards.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl656766 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q16</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>Does the data and model comply with ethical requirements?<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl656766 width=368 style='border-top:none;border-left:none;
  width:276pt'>T6 Organisations should look after people’s information securely
  and manage data in ways that are consistent with relevant legislation and
  serve the public good. T1.1 Everyone that works in organisations producing
  official statistics should handle and use statistics and data with honesty
  and integrity, guided by established principles of appropriate behaviour in
  public life.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=167 style='height:125.0pt'>
  <td height=167 class=xl656766 width=31 style='height:125.0pt;border-top:none;
  width:24pt'>Q17</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>What questions are outside the scope of the analysis?</td>
  <td class=xl656766 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q1.6 The causes of limitations in data sources should be
  identified and addressed where possible. Statistics producers should be open
  <br>
    about the extent to which limitations can be overcome and the impact on the
  statistics. Q2.4 Relevant limitations arising from the methods and their
  application, including bias and uncertainty, should be identified and
  explained to users. An indication of their likely scale and the steps taken
  to reduce their impact on the statistics should be included in the explanation.</td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl656766 width=31 style='height:100.0pt;border-top:none;
  width:24pt'>Q18</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>Will internal auditing and peer review be performed?</td>
  <td class=xl656766 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q3 Producers of statistics and data should explain clearly how
  they assure themselves that statistics and data are accurate, reliable,
  coherent and timely. T4.6 Independent measures, such as internal and external
  audit, peer review and National Statistics Quality Reviews, should be used to
  evaluate the effectiveness of statistical processes. Statistics producers
  should be open about identified areas for improvement.</td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl656766 width=31 style='height:100.0pt;border-top:none;
  width:24pt'>Q19</td>
  <td class=xl656766 width=321 style='border-top:none;border-left:none;
  width:241pt'>Will external experts be involved in development and scruitny of
  analysis?</td>
  <td class=xl676766 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q3 Assured quality Producers of statistics and data should
  explain clearly how they assure themselves that statistics and data are
  accurate, reliable, coherent and timely. T4.6 Independent measures, such as
  internal and external audit, peer review and National Statistics Quality
  Reviews, should be used to evaluate the effectiveness of statistical
  processes. Statistics producers should be open about identified areas for
  improvement.</td>
  </tr>
</table>

## Aqua Roles and Responsibilities

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
<TR VALIGN=TOP>
    <th> </th>
    <th> Quality Questions</th>
    <th> Who is responsible for answering this in light of AQUA book?</th>
    <th> Which AQUA book responsibilities have a role?</th>

</tr>
 <tr height=83 style='height:62.5pt'>

<td height=67 class=xl6521709 width=31 style='height:50.0pt;width:24pt'>Q1</td>
  <td class=xl6521709 width=321 style='border-left:none;width:241pt'>What
  question is the analysis trying to answer?</td>
  <td class=xl6521709 width=182 style='border-left:none;width:137pt'>Commissioner,
  analyst</td>
  <td class=xl6521709 width=299 style='border-left:none;width:225pt'>The
  commissioner plays an essential role in communicating the commission and
  working with the analyst to ensure that an appropriate understanding of the
  problem is captured.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6521709 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q2</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>Why do we need to answer this question?</td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner, analyst, analytical assurer</td>
  <td class=xl6521709 width=299 style='border-top:none;border-left:none;
  width:225pt'>The analyst must document the purpose of the analysis and the
  levels of quality and certainty that are required for this purpose.
  Commissioner and analytical assurer should make sure the work aligns with the
  stated purpose.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6521709 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q3</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>Which organisational priorities does this work address?</td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner</td>
  <td class=xl6521709 width=299 style='border-top:none;border-left:none;
  width:225pt'>The commissioner is responsible for ensuring that key aspects of
  the problem, scope and complexities, including programme constraints, are
  captured and clearly communicated and there is proportionate governance in
  place to support the analysis and its role in the wider project or
  programme<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=183 style='height:137.5pt'>
  <td height=183 class=xl6521709 width=31 style='height:137.5pt;border-top:
  none;width:24pt'>Q4</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is the model business critical?</td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner</td>
  <td class=xl6521709 width=299 style='border-top:none;border-left:none;
  width:225pt'>All business critical models in government should be managed
  within a framework that ensures appropriately specialist staff are
  responsible for developing and using the models as well as quality assurance.
  In such situations, it is important that the decision-maker has sufficient
  assurance from a senior level within the organisation before taking the
  decision. For business critical analysis and modelling, the commissioner
  should be satisfied with the seniority of the analytical assurer.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6521709 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q5</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>Who needs to know the answer?</td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner,analyst,<span style='mso-spacerun:yes'> 
  </span>analytical assurer</td>
  <td class=xl6521709 width=299 style='border-top:none;border-left:none;
  width:225pt'>Commissioner should ensure appropriate stakeholders have been
  identified so that the scope and boundaries of the problem can be
  appropriately explored. Analyst and analytical assurer should also be
  involved.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6521709 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q6</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>Who do we need to consult to make sure we meet the right user
  needs?</td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, commissioner</td>
  <td class=xl6521709 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analyst should explore the requirements, boundaries, and scope
  with all of the stakeholders ensuring a wide range of perspectives are
  sought. Commissioner should be involved.</td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl6521709 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q7</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>How will you know you have answered this question correctly?</td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner, analyst</td>
  <td class=xl6521709 width=299 style='border-top:none;border-left:none;
  width:225pt'>During the design and conduct of analysis phases, the
  commissioner may need to provide the analyst with important information on
  the level of precision and accuracy required.<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6521709 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q8</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>What is the estimated time and resource required to answer this
  question (in months)?</td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner, analyst</td>
  <td class=xl6521709 width=299 style='border-top:none;border-left:none;
  width:225pt'>When commissioning a piece of analysis, a project is established
  and the typical project trade-offs between time, resources and quality must
  be made, recorded and communicated to the analyst. The analyst may also have
  a role in working with the commissioner to establish the optimal balance of
  these constraints.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6521709 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q9</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>What are the consequences if the work is not carried out now?</td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner</td>
  <td class=xl6721709 width=299 style='border-top:none;border-left:none;
  width:225pt'>The commissioner has a role to ensure that there is sufficient
  time and resource for the required level of assurance to be delivered and
  that they understand the associated risks when time and resource pressures
  are unavoidable</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl6521709 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q10</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>What are the consequences if the work is not carried out
  correctly?</td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner, analyst</td>
  <td class=xl6521709 width=299 style='border-top:none;border-left:none;
  width:225pt'>The commissioner must ensure that the analyst understands the
  context of the question being asked. This is so that the latter understands
  and can assess the likely risks and determine what the appropriate analytical
  and quality assurance response should be.<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6521709 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q11</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>Who is the commissioner, SRO and analytical assurer of this
  analysis?</td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner</td>
  <td class=xl6521709 width=299 style='border-top:none;border-left:none;
  width:225pt'>During the engagement phase of the analytical cycle, the
  commissioner is responsible for ensuring that there is proportionate
  governance in place to support the analysis and its role in the wider project
  or programme.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6521709 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q12</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>What tools and resources will you use during the production
  process? Are they the best for the job?</td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner</td>
  <td class=xl6521709 width=299 style='border-top:none;border-left:none;
  width:225pt'>The commissioner has a role to ensure that there is sufficient
  time and resource for the required level of assurance to be delivered and
  that they understand the associated risks when time and resource pressures
  are unavoidable.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6521709 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q13</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>Do you have the right internal and external resources and
  capability to deliver the analysis?</td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner</td>
  <td class=xl6521709 width=299 style='border-top:none;border-left:none;
  width:225pt'>The commissioner has a role to ensure that there is sufficient
  time and resource for the required level of assurance to be delivered and
  that they understand the associated risks when time and resource pressures
  are unavoidable.</td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6521709 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q14</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>What are the anticipated risks of the analysis? Have you
  discussed this risk with the customers?<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analytical assurer, commissioner, analyst</td>
  <td class=xl6521709 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analystical assurer should challenge and test the understanding
  of the problem. Commissioner and analyst should be involved.<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=250 style='height:187.5pt'>
  <td height=250 class=xl6521709 width=31 style='height:187.5pt;border-top:
  none;width:24pt'>Q15</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>Have you developed a contingency plan to put in place if the
  mitigation plan fails?</td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner, Analytical assurer</td>
  <td class=xl6721709 width=299 style='border-top:none;border-left:none;
  width:225pt'>The commissioner has a role to ensure that there is sufficient
  time and resource for the required level of assurance to be delivered and
  that they understand the associated risks when time and resource pressures
  are unavoidable. If there is a need for urgent action, such as a precaution
  against unacceptable but uncertain risks, the commissioner may request
  further analysis or evidence-gathering be commissioned in parallel to inform
  subsequent adjustments of the policy response when uncertainty is reduced.
  The analytical assurer is responsible for advising the commissioner on
  whether appropriate analytical quality assurance has taken place and advising
  them of any outstanding risks.</td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6521709 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q16</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>Does the data and model comply with ethical requirements?<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, commissioner, analytical assurer</td>
  <td class=xl6521709 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analyst should ensure that, if required, formal ethical approval
  is provided. Commissioner and analytical assurer should be involved.</td>
 </tr>
 <tr height=150 style='height:112.5pt'>
  <td height=150 class=xl6521709 width=31 style='height:112.5pt;border-top:
  none;width:24pt'>Q17</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>What questions are outside the scope of the analysis?</td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner, analyst</td>
  <td class=xl6521709 width=299 style='border-top:none;border-left:none;
  width:225pt'>There should be a clear understanding of the requirements and
  scope between the commissioner and the analyst at the commissioning stage.
  During the engagement phase of the analytical cycle, the commissioner is
  responsible for ensuring that key aspects of the problem, scope and
  complexities, including programme constraints, are captured and clearly
  communicated.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6521709 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q18</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>Will internal auditing and peer review be performed?</td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analytical assurer, commissioner, analyst</td>
  <td class=xl6521709 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analytical assurer should ensure the level of quality checking
  of the analysis is appropriate for the decision being supported: All analysis
  requires some checks, at some level, by another competent person wherever and
  whenever practicable. Analyst and commissioner should be involved.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6521709 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q19</td>
  <td class=xl6521709 width=321 style='border-top:none;border-left:none;
  width:241pt'>Will external experts be involved in development and scruitny of
  analysis?</td>
  <td class=xl6521709 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analytical assurer, commissioner, analyst</td>
  <td class=xl6521709 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analytical assurer should dry run the proposed approach to see
  if it delivers as intended. Then consider if the overall approach adequately
  addresses the complexities of the customer issue for this purpose. It is good
  practice to engage subject matter experts in this review. Analyst and
  commissioner should be involved.</td>
  </tr>
</table>


:::

## II. Design

::: {.panel-tabset}

## Quality Questions

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<table style="width:100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse; font size="2" face="Courier New">
<TR VALIGN=TOP>
    <th> </th>
    <th style="width:50%; text-align: center;"> Questions</th>
    <th style="width:50%; text-align: center;">Answers</th>
    <th style="text-align: center"> Answer added by</th>
    <th style="text-align: center"> Date answer added</th>
    <th style="text-align: center"> Is SRO satisfied with the answer?</th>
    <th style="text-align: center"> Next review due on</th>
    <th style="text-align: center"> Has anything changed from last review?</th>



</tr>
 <tr height=83 style='height:62.5pt'>
<td height=21 class=xl657005 width=31 style='height:15.5pt;width:24pt'>Q20</td>
  <td class=xl657005 width=321 style='border-left:none;width:241pt'>	Is there a simple description in plain English of what the analysis is for and what it does?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl657005 width=31 style='height:15.5pt;border-top:none;
  width:24pt'>Q21</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Does the analysis have a logic flowchart which explains the end-to-end conceptual steps in the work flow?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q22</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>When do you expect to start and finish each stage of analysis i.e., data collection, processing, quality assuarnce, analaysis and dissemination?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl657005 width=31 style='height:15.5pt;border-top:none;
  width:24pt'>Q23</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Does any part of the analysis rely on manual processing? Have you considered the cost and benefits of fully automating the process?	</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl657005 width=31 style='height:15.5pt;border-top:none;
  width:24pt'>Q24</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>What happens if any of your team members, reviewers or users find a mistake in your analysis? Do you have a clear and efficient process for addressing the concern and preventing it from happening again?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q25</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Have you assessed uncertainty?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

  </tr>
</table>


## Importance 

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
<TR VALIGN=TOP>
    <th> </th>
    <th> Questions</th>
    <th> Why do I need to know the answer to this?</th>

</tr>
 <tr height=83 style='height:62.5pt'>

<td height=67 class=xl666956 width=31 style='height:50.0pt;width:24pt'>Q20</td>
  <td class=xl666956 width=319 style='border-left:none;width:240pt'>Is there a
  simple description in plain English of what the analysis is for and what it
  does?</td>
  <td class=xl666956 width=396 style='border-left:none;width:297pt'>Writing a
  plain English description of what the analysis is for and how it works helps
  the team to assure themselves that they as well as others with no subject
  related or technical expertise can understand what the analysis is for and
  broadly how it works.</td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl666956 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q21</td>
  <td class=xl666956 width=319 style='border-top:none;border-left:none;
  width:240pt'>Does the analysis have a logic flowchart which explains the
  end-to-end conceptual steps in the work flow?</td>
  <td class=xl666956 width=396 style='border-top:none;border-left:none;
  width:297pt'>Setting out a clear summary of the analysis process in a diagram
  helps the team, users and customers to understand at a glance what the
  analysis does, where inputs come from, how they are processed and how outputs
  are generated.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl666956 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q22</td>
  <td class=xl666956 width=319 style='border-top:none;border-left:none;
  width:240pt'>When do you expect to start and finish each stage of analysis
  i.e., data collection, processing, quality assuarnce, analaysis and
  dissemination?</td>
  <td class=xl666956 width=396 style='border-top:none;border-left:none;
  width:297pt'>It is important to clearly set out the time requied to perform
  each stage of analysis from start to finish. It would help the team to
  evaluate if the current balance of the time split across these stages looks
  effective and challenge it if the target looks so ambitious.<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl666956 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q23</td>
  <td class=xl666956 width=319 style='border-top:none;border-left:none;
  width:240pt'>Does any part of the analysis rely on manual processing? Have
  you considered the cost and benefits of fully automating the process?</td>
  <td class=xl666956 width=396 style='border-top:none;border-left:none;
  width:297pt'>Manual processes are often inefficient and prone to user error -
  a manual process is inherently more risky than a well-designed automated one.
  Analysis with lots of manual steps (e.g. copying and pasting data from one
  file to another, updating cells in spreadsheets, or moving data between
  software packages with separate steps in each) is harder to assure and
  carries extra quality risks.</td>
 </tr>
 <tr height=167 style='height:125.0pt'>
  <td height=167 class=xl666956 width=31 style='height:125.0pt;border-top:none;
  width:24pt'>Q24</td>
  <td class=xl666956 width=319 style='border-top:none;border-left:none;
  width:240pt'>What happens if any of your team members, reviewers or users
  find a mistake in your analysis? Do you have a clear and efficient process
  for addressing the concern and preventing it from happening again?</td>
  <td class=xl666956 width=396 style='border-top:none;border-left:none;
  width:297pt'>Mistakes happen in analysis. There should be a clear and
  efficient process for reporting, documenting and addressing errors and
  mistakes that you find. Being open and honest about problems and working
  together to solve them in a supportive way creates an atmosphere of openness
  within your team and is critical for upholding users' trust in your output.
  Your team should take reasonable steps to understand and document how and why
  errors came about and mitigate the risk of a similar error happening again. The
  mitigation approach should be consistent with your department's revision
  policies.</td>
 </tr>
 <tr height=150 style='height:112.5pt'>
  <td height=150 class=xl666956 width=31 style='height:112.5pt;border-top:none;
  width:24pt'>Q25</td>
  <td class=xl666956 width=319 style='border-top:none;border-left:none;
  width:240pt'>Have you assessed uncertainty?</td>
  <td class=xl666956 width=396 style='border-top:none;border-left:none;
  width:297pt'>Uncertainty should be considered holistically throughout the
  analytical process. You should identify and review sources of uncertainty
  regularly, and bring it into your thinking as early as possible. Leaving the
  consideration of uncertainty until late in the process can be difficult and
  costly in time and resources. It may require you to revise the process or
  alter commissioning decisions accordingly. Moreover, if a potential source of
  uncertainty is overlooked at the begining, it could reduce the usefulness and
  impact of the analysis.<span style='mso-spacerun:yes'> </span></td>
  </tr>
</table>

## Code of Practice for Statistics

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
<TR VALIGN=TOP>
    <th> </th>
    <th> Questions</th>
    <th> Which pillar and principle of Code of Practice are relevant here?  
    *Trustworthiness (T), Quality (Q), Value (V)</th>

</tr>
 <tr height=83 style='height:62.5pt'>

<td height=50 class=xl656956 width=31 style='height:37.5pt;width:24pt'>Q20</td>
  <td class=xl656956 width=321 style='border-left:none;width:241pt'>Is there a
  simple description in plain English of what the analysis is for and what it
  does?</td>
  <td class=xl676956 width=368 style='border-left:none;width:276pt'>V3
  Statistics and data should be presented clearly, explained meaningfully and
  provide authoritative insights that serve the public good.</td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl656956 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q21</td>
  <td class=xl656956 width=321 style='border-top:none;border-left:none;
  width:241pt'>Does the analysis have a logic flowchart which explains the
  end-to-end conceptual steps in the work flow?</td>
  <td class=xl676956 width=368 style='border-top:none;border-left:none;
  width:276pt'>V3 Statistics and data should be presented clearly, explained
  meaningfully and provide authoritative insights that serve the public good.</td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl656956 width=31 style='height:100.0pt;border-top:none;
  width:24pt'>Q22</td>
  <td class=xl656956 width=321 style='border-top:none;border-left:none;
  width:241pt'>When do you expect to start and finish each stage of analysis
  i.e., data collection, processing, quality assuarnce, analaysis and
  dissemination?</td>
  <td class=xl656956 width=368 style='border-top:none;border-left:none;
  width:276pt'>T3.5 Statistics and data should be released on a timely basis
  and at intervals that meet the needs of users as far as practicable. The
  statistics should be released as soon as they are considered ready, under the
  guidance of the Chief Statistician/Head of Profession for Statistics. Q3.3
  The quality of the statistics and data, including their accuracy and
  reliability, coherence and comparability, and timeliness<span
  style='mso-spacerun:yes'>  </span>and punctuality, should be monitored and
  reported regularly.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl656956 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q23</td>
  <td class=xl656956 width=321 style='border-top:none;border-left:none;
  width:241pt'>Does any part of the analysis rely on manual processing? Have
  you considered the cost and benefits of fully automating the process?</td>
  <td class=xl656956 width=368 style='border-top:none;border-left:none;
  width:276pt'>V4 Statistics producers should be creative and motivated to
  improve statistics and data, recognising the potential to harness
  technological advances for the development of all parts of the production and
  dissemination process. T4.3 Sufficient human, financial and technological
  resources should be provided to deliver statistical services that serve the
  public good.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl656956 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q24</td>
  <td class=xl656956 width=321 style='border-top:none;border-left:none;
  width:241pt'>What happens if any of your team members, reviewers or users
  find a mistake in your analysis? Do you have a clear and efficient process
  for addressing the concern and preventing it from happening again?</td>
  <td class=xl656956 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q3.4 Scheduled revisions, or unscheduled corrections that result
  from errors, should be explained alongside the statistics, being clear on
  <br>
    the scale, nature, cause and impact. V5 Statistics and data should be
  published in forms that enable their reuse. Producers should use existing
  data wherever possible and only ask for more where justified.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl656956 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q25</td>
  <td class=xl656956 width=321 style='border-top:none;border-left:none;
  width:241pt'>Have you assessed uncertainty?</td>
  <td class=xl656956 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q2.4 Relevant limitations arising from the methods and their
  application, including bias and uncertainty, should be identified and
  explained to users. An indication of their likely scale and the steps taken
  to reduce their impact on the statistics should be included in the
  explanation.</td>
  </tr>
</table>

## Aqua Roles and Responsibilities

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
<TR VALIGN=TOP>
    <th> </th>
    <th> Questions</th>
    <th> Who is responsible for answering this in light of AQUA book?</th>
    <th> Which AQUA book responsibilities have a role?</th>

</tr>
 <tr height=83 style='height:62.5pt'>

 <td height=100 class=xl6511553 width=31 style='height:75.0pt;width:24pt'>Q20</td>
  <td class=xl6511553 width=321 style='border-left:none;width:241pt'>Is there a
  simple description in plain English of what the analysis is for and what it
  does?</td>
  <td class=xl6511553 width=182 style='border-left:none;width:137pt'>Analyst,
  analytical assurer</td>
  <td class=xl6511553 width=299 style='border-left:none;width:225pt'>Analyst
  should produce appropriate design documentation. Best practice can include a
  concept of analysis, user requirements, design specification, functional
  specification, data dictionary, and test plan. Analytical assurer should be
  involved.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl6511553 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q21</td>
  <td class=xl6511553 width=321 style='border-top:none;border-left:none;
  width:241pt'>Does the analysis have a logic flowchart which explains the
  end-to-end conceptual steps in the work flow?</td>
  <td class=xl6511553 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, analytical assurer</td>
  <td class=xl6511553 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analyst should produce appropriate design documentation. Best
  practice can include a concept of analysis, user requirements, design
  specification, functional specification, data dictionary, and test plan.
  Analytical assurer should be involved.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6511553 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q22</td>
  <td class=xl6511553 width=321 style='border-top:none;border-left:none;
  width:241pt'>When do you expect to start and finish each stage of analysis
  i.e., data collection, processing, quality assuarnce, analaysis and
  dissemination?</td>
  <td class=xl6511553 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner, analyst</td>
  <td class=xl6511553 width=299 style='border-top:none;border-left:none;
  width:225pt'>When commissioning a piece of analysis, a project is established
  and the typical project trade-offs between time, resources and quality must
  be made, recorded and communicated to the analyst. The analyst may also have
  a role in working with the commissioner to establish the optimal balance of
  these constraints.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl6511553 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q23</td>
  <td class=xl6511553 width=321 style='border-top:none;border-left:none;
  width:241pt'>Does any part of the analysis rely on manual processing? Have
  you considered the cost and benefits of fully automating the process?</td>
  <td class=xl6511553 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner, analyst</td>
  <td class=xl6711553 width=299 style='border-top:none;border-left:none;
  width:225pt'>The analyst should use a risk-based approach to highlight the
  areas of greatest potential error and focus assurance efforts on these areas.
  It is important that the impact of any reduction in the thoroughness of
  analytical quality assurance activities is understood by the
  commissioner.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6511553 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q24</td>
  <td class=xl6511553 width=321 style='border-top:none;border-left:none;
  width:241pt'>What happens if any of your team members, reviewers or users
  find a mistake in your analysis? Do you have a clear and efficient process
  for addressing the concern and preventing it from happening again?</td>
  <td class=xl6511553 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, analytical assurer</td>
  <td class=xl6711553 width=299 style='border-top:none;border-left:none;
  width:225pt'>The analyst should use a risk-based approach to highlight the
  areas of greatest potential error and focus assurance efforts on these areas.</td>
 </tr>
 <tr height=200 style='height:150.0pt'>
  <td height=200 class=xl6511553 width=31 style='height:150.0pt;border-top:
  none;width:24pt'>Q25</td>
  <td class=xl6511553 width=321 style='border-top:none;border-left:none;
  width:241pt'>Have you assessed uncertainty?</td>
  <td class=xl6511553 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner, analyst</td>
  <td class=xl6511553 width=299 style='border-top:none;border-left:none;
  width:225pt'>Commissioners should request and expect information on
  uncertainty from analysts, and challenge them when it is absent, inadequate
  or ambiguous. In addition, commissioners of analysis may have identified
  sources of uncertainty as part of their wider considerations and should
  communicate these to the analyst. If it is possible for the commissioner to
  indicate in advance the consequences for decision-making of different degrees
  of uncertainty, this may enable the analyst to conduct their analysis at a
  proportionate level.<span style='mso-spacerun:yes'> </span></td>

  </tr>
</table>

:::

## III. Conducting and Checking Analysis


::: {.panel-tabset}


## Quality Questions

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<table style="width:100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse; font size="2" face="Courier New">
<TR VALIGN=TOP>
    <th> </th>
    <th style="width:50%; text-align: center;"> Questions</th>
    <th style="width:50%; text-align: center;">Answers</th>
    <th style="text-align: center"> Answer added by</th>
    <th style="text-align: center"> Date answer added</th>
    <th style="text-align: center"> Is SRO satisfied with the answer?</th>
    <th style="text-align: center"> Next review due on</th>
    <th style="text-align: center"> Has anything changed from last review?</th>


</tr>
 <tr height=83 style='height:62.5pt'>
<td height=21 class=xl657005 width=31 style='height:15.5pt;width:24pt'>Q26</td>
  <td class=xl657005 width=321 style='border-left:none;width:241pt'>How the data used in the analysis will be processed prior to and during use?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl657005 width=31 style='height:15.5pt;border-top:none;
  width:24pt'>Q27</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	Is the data appropriate given the methods selected?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q28</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>What are the strengths and limitations of the data that you use?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl657005 width=31 style='height:15.5pt;border-top:none;
  width:24pt'>Q29</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	Is there a robust relationship between your team and data providers? Does your data provider have a good understanding of how and why you are using their data?
Do you have a good understanding of how the data provider collects, processes and quality assures the data?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl657005 width=31 style='height:15.5pt;border-top:none;
  width:24pt'>Q30</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	Is there a formal agreement in place that specifies when, what and how the data will be received? If not, do you think this would be helpful?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q31</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Do you know what quality checks are carried out on the data before you receive them?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q32</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>How will you work with your data provider when your data requirements change?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q33</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	How do you know if your data provider makes a change to their systems or processes, which could impact the data you receive and/or the statistics you produce?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q34</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>How did you choose the methods for the analysis? How do you know the method you are using is appropriate? </td>
  
  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>
 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q35</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Are reasonable alternative methods have been explored and rejected for good reasons?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q36</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>How do you know that your analysis or statistical process is working correctly?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q37</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Can you describe the assumptions of your analysis, when they were made and who made them and signed them off?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q38</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>How the assumptions are validated and assured prior to use?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q39</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	How do you measure and report uncertainty in your analysis?<span
  style='mso-spacerun:yes'> </span></td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q40</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	Have you considered the implications of any unquantified uncertainties?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q41</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Can you explain the impact of your work/output on downstream processes? Are there any risks around these dependencies?<span
  style='mso-spacerun:yes'> </span></td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q42</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>All or part of the analysis is reliant on a single person?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl657005 width=31 style='height:15.5pt;border-top:none;
  width:24pt'>Q43</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	Is it clear why important decisions were made and who made them?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q44</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	If changes need to be made to any code or datasets, is it difficult to track who made these changes and why those changes were made? </td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q45</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	Would another analyst be able to reproduce your model output or continue the work (without talking to you first)? </td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

  </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q46</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	Do you use internal peer review to check scripts and code, documentation, implementation of methods, processes and outputs? </td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>
  
  </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q47</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	Is your code and analysis ever peer reviewed by someone outside your team or organisation?<span
  style='mso-spacerun:yes'> </span></td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q48</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	What is the assessment of the quality of your analytical outputs?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl657005 width=31 style='height:15.5pt;border-top:none;
  width:24pt'>Q49</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	How do you assure yourselves that analysis carried out is correct?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q50</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>		Do the outputs of your analysis match reported content? </td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q51</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	If you find outliers or unusual trends in the data, what steps are taken to investigate them? </td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>
  </tr>
</table>



## Importance 

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
<TR VALIGN=TOP>
    <th> </th>
    <th> Questions</th>
    <th> Why do I need to know the answer to this?</th>

</tr>
 <tr height=83 style='height:62.5pt'>

<td height=67 class=xl6619059 width=31 style='height:50.0pt;width:24pt'>Q26</td>
  <td class=xl6619059 width=319 style='border-left:none;width:240pt'>How the
  data used in the analysis will be processed prior to and during use?</td>
  <td class=xl6619059 width=396 style='border-left:none;width:297pt'>Operations
  on the data inputs will have wide-ranging effects on processes and outputs. A
  clear understanding of how these processes affect the workflow is essential
  for understanding quality.</td>
 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl6619059 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q27</td>
  <td class=xl6619059 width=319 style='border-top:none;border-left:none;
  width:240pt'>Is the data appropriate given the methods selected?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>A comprehensive understanding of data inputs is a prerequisite
  to meeting user needs.</td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl6619059 width=31 style='height:100.0pt;border-top:
  none;width:24pt'>Q28</td>
  <td class=xl6619059 width=319 style='border-top:none;border-left:none;
  width:240pt'>What are the strengths and limitations of the data that you
  use?<span style='mso-spacerun:yes'> </span></td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>Not all data can be usd to answer particular research questions.
  The formatting, the time scale, the granularity must all be assessed and
  found relevant to the research question. A comprehensive understanding of
  data inputs is a prerequisite to meeting user needs. Without understanding
  where data is strong and where it is weak, it is impossible to make
  meaningful improvements to the analysis and/or the inputs to manage the
  limitations.<span style='mso-spacerun:yes'>    </span></td>
 </tr>
 <tr height=167 style='height:125.0pt'>
  <td height=167 class=xl6619059 width=31 style='height:125.0pt;border-top:
  none;width:24pt'>Q29</td>
  <td class=xl6619059 width=319 style='border-top:none;border-left:none;
  width:240pt'>Is there a robust relationship between your team and data
  providers? Does your data provider have a good understanding of how and why
  you are using their data?<br>
    Do you have a good understanding of how the data provider collects,
  processes and quality assures the data?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>A good relationship with data suppliers helps to make sure that
  the data they supply meet your requirements. Lack of communication can mean
  you are not aware of quality risks or changes in collection or processing
  steps that may affect your results. You should be able to communicate with
  your suppliers as often as you need to to manage input quality. Data
  providers should also have a good understanding of how and why you are using
  their data. This can help them to improve data quality, value, and identify
  and address any gaps or issues that are relevant for your analysis.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl6619059 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q30</td>
  <td class=xl6719059 width=319 style='border-top:none;border-left:none;
  width:240pt'>Is there a formal agreement in place that specifies when, what
  and how the data will be received? If not, do you think this would be
  helpful?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>A formal agreement with data providers makes sure that everybody
  understands what will be delivered, when and how. It is useful for setting
  out clearly the division of responsibilities between data providers and your
  team for acessing and sharing the data, for example, formats, delivery,
  timescale, legal framework, accompanying metadata and quality checks.<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl6619059 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q31</td>
  <td class=xl6719059 width=319 style='border-top:none;border-left:none;
  width:240pt'>Do you know what quality checks are carried out on the data
  before you receive them?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>Data suppliers should be able to demonstrate that their data has
  been well assured and meets your needs. If there is no evidence of this it is
  cause for concern. Simply having a quality report is not enough. You should
  have sufficient evidence to understand that the data meet your needs and that
  reported quality matches what you observe in practice.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6619059 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q32</td>
  <td class=xl6719059 width=319 style='border-top:none;border-left:none;
  width:240pt'>How will you work with your data provider when your data
  requirements change?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>You should review your data requirements regularly to ensure
  they are still relevant and feasible. Any change in requirements should be
  communicated to data providers well in advance and agreed upon by all
  stakeholders. If there is a formal agreement, it may need to be revised as
  requirements change.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6619059 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q33</td>
  <td class=xl6719059 width=319 style='border-top:none;border-left:none;
  width:240pt'>How do you know if your data provider makes a change to their
  systems or processes, which could impact the data you receive and/or the
  statistics you produce?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>Often the data suppliers make changes to their methodology or
  systems. This may not necessarily affect the quality of their data but it may
  impact on how you are processing this data and what findings can you infer
  from it. We consider it important to demonstrate that bilateral commuication
  between data supplier and your team is frequent, effective and ongoing so
  that you get timely information about any changes made by them.<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6619059 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q34</td>
  <td class=xl6719059 width=319 style='border-top:none;border-left:none;
  width:240pt'>How did you choose the methods for the analysis? How do you know
  the method you are using is appropriate?<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>You should be able to explain why you chose the method by
  explaining the underlying assumptions of the method, its suitabilty for
  answering the research question and for the type and distribution of data you
  are using, and how was this decision signed off.</td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl6619059 width=31 style='height:100.0pt;border-top:
  none;width:24pt'>Q35</td>
  <td class=xl6619059 width=319 style='border-top:none;border-left:none;
  width:240pt'>Are reasonable alternative methods have been explored and
  rejected for good reasons?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>There is usually more than one way to answer a research question
  and meet the objectives of an analysis. By explaining why other
  methods/approaches were considered and rejected in favour of the method
  selected, your team and users can be confident that the chosen method is
  appropriate. Unless there is evidence underpinning your choice, users cannot
  be sure that you have alternate methods have been explored and rejected for
  good reasons.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6619059 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q36</td>
  <td class=xl6719059 width=319 style='border-top:none;border-left:none;
  width:240pt'>How do you know that your analysis or statistical process is
  working correctly?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>You need to be sure that your analysis produces the outputs that
  you think it should and that the processes you run work as expected. If you
  cannot demonstrate that scripts and processes you have set up are functioning
  correctly, you cannot confirm the quality of the results.</td>
 </tr>
 <tr height=183 style='height:137.5pt'>
  <td height=183 class=xl6619059 width=31 style='height:137.5pt;border-top:
  none;width:24pt'>Q37</td>
  <td class=xl6719059 width=319 style='border-top:none;border-left:none;
  width:240pt'>Can you describe the assumptions of your analysis, when they
  were made and who made them and signed them off?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>A clear undersatnding of assumptions is important for
  understanding how the model/analysis simplifies the world and to mitigate the
  uncertainties present in every analysis. If assumptions are inadequately set
  out or absent, assumed characteristics about the analysis and its inputs will
  be opaque, greatly increasing risk. Without a comprehensive log of all
  assumptions made by the model, an audit trail back to sources signed off by
  assumption owners, a version control log reflecting when assumptions were last
  updated and evidence reflecting internal and external validation of
  assumptions, uncertainties may go unacknowledged and could drastically impact
  the outputs.<span style='mso-spacerun:yes'>  </span></td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6619059 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q38</td>
  <td class=xl6619059 width=319 style='border-top:none;border-left:none;
  width:240pt'>How the assumptions are validated and assured prior to use?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>A clear understanding of how assumptions have been externall and
  internally validated and signed off gives us confidence that they are
  reasonable.</td>
 </tr>
 <tr height=233 style='height:175.0pt'>
  <td height=233 class=xl6619059 width=31 style='height:175.0pt;border-top:
  none;width:24pt'>Q39</td>
  <td class=xl6719059 width=319 style='border-top:none;border-left:none;
  width:240pt'>How do you measure and report uncertainty in your analysis?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>All analysis contain some degree of uncertainty that may come
  from a variety of sources. Reporting uncertainties is important to inform
  users of how precisely we can give our reported values or how much confidence
  users can have in the analysis. It could also help your team to determine
  where an analysis can be improved. There are many ways to quantify
  uncertainty in input data, assumptions, processes and outputs. There is no
  ‘one size fits all’ approach. For instance, the size and distribution of the
  uncertainties in analytical inputs can be understood by comparing different
  data sources, understanding the probability distribution, break-even
  analysis, using expert judgement or historical data to inform ranges.
  Uncertainty in model outputs can be assessed with Monte Carlo techniques,
  convolution, scenario analysis,<span style='mso-spacerun:yes'> 
  </span>previous forecasts, expert judgement, etc.</td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6619059 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q40</td>
  <td class=xl6619059 width=319 style='border-top:none;border-left:none;
  width:240pt'>Have you considered the implications of any unquantified
  uncertainties?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>A good understanding of the uncertainties in the analysis
  workflow is critical to ensure the model and its outputs are fit for purpose.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6619059 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q41</td>
  <td class=xl6619059 width=319 style='border-top:none;border-left:none;
  width:240pt'>Can you explain the impact of your work/output on downstream
  processes? Are there any risks around these dependencies?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>Understanding how your analysis would be used by the primary and
  secondary users would help to ensure that the right quality and assurance
  levels are in place. It would help you to assess the risks around the use of
  analysis and if there are other stakeholders or users you need to
  consult.<span style='mso-spacerun:yes'>            </span></td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6619059 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q42</td>
  <td class=xl6719059 width=319 style='border-top:none;border-left:none;
  width:240pt'>All or part of the analysis is reliant on a single person?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>Single points of failure carry significant business risk. If
  there is only one person who understands how to carry out all or part of the
  analysis then the process is extremely vulnerable.</td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl6619059 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q43</td>
  <td class=xl6619059 width=319 style='border-top:none;border-left:none;
  width:240pt'>Is it clear why important decisions were made and who made them?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>All analysis involves decisions. A comprehensive record of the
  decisions made in specifying and conducting the analysis ensures that we have
  a full audit trail of why decisions were made, who made them and signed them
  off.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6619059 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q44</td>
  <td class=xl6719059 width=319 style='border-top:none;border-left:none;
  width:240pt'>If changes need to be made to any code or datasets, is it
  difficult to track who made these changes and why those changes were
  made?<span style='mso-spacerun:yes'> </span></td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>Good version control ensures that you have a full understanding
  of when, why and how changes were made to your analysis process. If it is
  hard to track changes, this makes it hard to retrace steps if there is a
  problem and means you do not fully understand the process</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6619059 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q45</td>
  <td class=xl6619059 width=319 style='border-top:none;border-left:none;
  width:240pt'>Would another analyst be able to reproduce your model output or
  continue the work (without talking to you first)?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>Your analysis must be well documented and repeatable so that
  somebody new can understand it, pick it up and produce the same output using
  the same inputs. Poor documentation means that other people will not
  understand why the process is configured as it is, how the process works, how
  to run the process safely and produce the same output- potentially leading to
  errors.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6619059 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q46</td>
  <td class=xl6719059 width=319 style='border-top:none;border-left:none;
  width:240pt'>Do you use internal peer review to check scripts and code,
  documentation, implementation of methods, processes and outputs?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>The team should independently review and validate the logical
  integrity of its analysis as well as the structure and functionality of the
  code against the research question the analysis asks. A record of validation
  and verification activities undertaken, outstanding activities and remedial
  actions is important to understand that the correct analysis has been
  performed for the purpose it is used for and the chosen approach minimises
  risk.</td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl6619059 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q47</td>
  <td class=xl6719059 width=319 style='border-top:none;border-left:none;
  width:240pt'>Is your code and analysis ever peer reviewed by someone outside
  your team or organisation?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>External peer review is one of the best ways to ensure that the
  analysis and code are well made and fit for purpose. Without it, teams may
  reinforce their own biases and will be unable to notice there is anything
  wrong.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl6619059 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q48</td>
  <td class=xl6719059 width=319 style='border-top:none;border-left:none;
  width:240pt'>What is the assessment of the quality of your analytical
  outputs?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>Understanding and reporting on the quality of your analytical
  outputs is critical to ensure fitness for purpose, as well as trust and
  reliability. This ensures that analysis can appropriately inform
  decision-making. Your quality assessments are also key information to be
  shared with your users as well as being a requirement of the Code of Practice
  for Statistics.</td>
 </tr>
 <tr height=150 style='height:112.5pt'>
  <td height=150 class=xl6619059 width=31 style='height:112.5pt;border-top:
  none;width:24pt'>Q49</td>
  <td class=xl6719059 width=319 style='border-top:none;border-left:none;
  width:240pt'>How do you assure yourselves that analysis carried out is
  correct?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>It is important to aasure the results fit with your expectations
  and you are able to explain why there are any discrepancies. It makes it
  easier to mitigate risk appropriately. There are various ways of assuring if
  the analysis is carried out correctly. For example, sensitivity analysis can
  help in understanding which inputs are having the greatest effect on the
  outputs, and which procesess within the model are the most critical.You can
  also compare figures from your analysis with any similar earlier analysis or
  test your data against historical series.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6619059 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q50</td>
  <td class=xl6619059 width=319 style='border-top:none;border-left:none;
  width:240pt'>Do the outputs of your analysis match reported content?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>Where possible, you should check that your outputs align with
  expectation from alternate data sources, previous methods and comparable
  studies. It would gives you confidence that the analysis is performing as
  expected. Your team should be able to explain any inconsistencies.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl6619059 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q51</td>
  <td class=xl6719059 width=319 style='border-top:none;border-left:none;
  width:240pt'>If you find outliers or unusual trends in the data, what steps
  are taken to investigate them?</td>
  <td class=xl6619059 width=396 style='border-top:none;border-left:none;
  width:297pt'>It is crucial to identify unusual trends in the data and
  understand why you had them there in the first place. Not all outliers are
  the same. Some have a strong influence, some not at all. Some are valid and
  important data values and some are simply errors. Outliers should be
  thoroughly investigated and reasonable steps should be taken to analyse their
  impact on your final output.</td>

  </tr>
</table>

## Code of Practice for Statistics

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
<TR VALIGN=TOP>
    <th> </th>
    <th> Questions</th>
    <th> Which pillar and principle of Code of Practice are relevant here?  
    *Trustworthiness (T), Quality (Q), Value (V)</th>

</tr>
 <tr height=83 style='height:62.5pt'>

<td height=50 class=xl6519059 width=31 style='height:37.5pt;width:24pt'>Q26</td>
  <td class=xl6519059 width=321 style='border-left:none;width:241pt'>How the
  data used in the analysis will be processed prior to and during use?</td>
  <td class=xl6519059 width=368 style='border-left:none;width:276pt'>Q1
  Statistics should be based on the most appropriate data to meet intended
  uses. The impact of any data limitations for use should be assessed,
  minimised and explained.</td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6519059 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q27</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is the data appropriate given the methods selected?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q1 Statistics should be based on the most appropriate data to
  meet intended uses. The impact of any data limitations for use should be
  assessed, minimised and explained.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl6519059 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q28</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>What are the strengths and limitations of the data that you
  use?<span style='mso-spacerun:yes'> </span></td>
  <td class=xl6719059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q1 Statistics should be based on the most appropriate data to
  meet intended uses. The impact of any data limitations for use should be
  assessed, minimised and explained. Q1.5 Potential bias, uncertainty and
  possible distortive effects in the source data should be identified and the
  extent of any impact on the statistics should be clearly reported.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6519059 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q29</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is there a robust relationship between your team and data
  providers? Does your data provider have a good understanding of how and why
  you are using their data?<br>
    Do you have a good understanding of how the data provider collects,
  processes and quality assures the data?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q1.2 Statistics producers should establish and maintain
  constructive relationships with those involved in the collection, recording,
  supply, linking and quality assurance of data, wherever possible.</td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl6519059 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q30</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is there a formal agreement in place that specifies when, what
  and how the data will be received? If not, do you think this would be
  helpful?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q1.3 A clear statement of data requirements should be shared
  with the organisations that provide that data, setting out decisions on
  timing, definitions and format of data supply, and explaining how and why the
  data will be used.</td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6519059 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q31</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>Do you know what quality checks are carried out on the data
  before you receive them?</td>
  <td class=xl6719059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q1 Statistics should be based on the most appropriate data to
  meet intended uses. The impact of any data limitations for use should be
  assessed, minimised and explained.</td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl6519059 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q32</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>How will you work with your data provider when your data
  requirements change?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q1.2 Statistics producers should establish and maintain
  constructive relationships with those involved in the collection, recording,
  supply, linking and quality assurance of data, wherever possible.</td>
 </tr>
 <tr height=150 style='height:112.5pt'>
  <td height=150 class=xl6519059 width=31 style='height:112.5pt;border-top:
  none;width:24pt'>Q33</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>How do you know if your data provider makes a change to their
  systems or processes, which could impact the data you receive and/or the
  statistics you produce?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q1.2 Statistics producers should establish and maintain
  constructive relationships with those involved in the collection, recording,
  supply, linking and quality assurance of data, wherever possible. Q1.7 The
  impact of changes in the circumstances and context of a data <br>
    source on the statistics over time should be evaluated. Reasons for any
  lack of consistency and related implications for use should be <br>
    clearly explained to users.</td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6519059 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q34</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>How did you choose the methods for the analysis? How do you know
  the method you are using is appropriate?<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl6719059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q2 Producers of statistics and data should use the best
  available methods and recognised standards, and be open about their
  decisions.</td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6519059 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q35</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>Are reasonable alternative methods have been explored and
  rejected for good reasons?</td>
  <td class=xl6719059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q2 Producers of statistics and data should use the best
  available methods and recognised standards, and be open about their
  decisions.</td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6519059 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q36</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>How do you know that your analysis or statistical process is
  working correctly?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q3 Producers of statistics and data should explain clearly how
  they assure themselves that statistics and data are accurate, reliable,
  coherent and timely.</td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl6519059 width=31 style='height:100.0pt;border-top:
  none;width:24pt'>Q37</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>Can you describe the assumptions of your analysis, when they
  were made and who made them and signed them off?</td>
  <td class=xl6819059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Transparency (cross cutting theme) is needed about processes,
  methodology and content. Transparency means being clear and open, for
  example, about the choices being made – and not holding back or being opaque
  about decisions. Within Quality, producers should explain what judgements
  they have made about the data and methods, and their strengths and
  limitations. These explanations are as important as the numbers themselves.</td>
 </tr>
 <tr height=200 style='height:150.0pt'>
  <td height=200 class=xl6519059 width=31 style='height:150.0pt;border-top:
  none;width:24pt'>Q38</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>How the assumptions are validated and assured prior to use?</td>
  <td class=xl6819059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Transparency (cross-cutting theme) is needed about processes,
  methodology and content. Transparency means being clear and open, for
  example, about the choices being made – and not holding back or being opaque
  about decisions. Within Quality, producers should explain what judgements
  they have made about the data and methods, and their strengths and
  limitations. These explanations are as important as the numbers themselves.
  Q3.5 Systematic and periodic reviews on the strengths and limitations in the
  data and methods should be undertaken. Statistics producers should be open in
  addressing the issues identified and be transparent about their decisions on
  whether to act.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6519059 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q39</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>How do you measure and report uncertainty in your analysis?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q2.4 Relevant limitations arising from the methods and their
  application, including bias and uncertainty, should be identified and
  explained to users. An indication of their likely scale and the steps taken
  to reduce their impact on the statistics should be included in the
  explanation.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6519059 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q40</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>Have you considered the implications of any unquantified
  uncertainties?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q2.4 Relevant limitations arising from the methods and their
  application, including bias and uncertainty, should be identified and
  explained to users. An indication of their likely scale and the steps taken
  to reduce their impact on the statistics should be included in the
  explanation. Q3.3 The extent and nature of any uncertainty in the estimates
  should be clearly explained.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6519059 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q41</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>Can you explain the impact of your work/output on downstream
  processes? Are there any risks around these dependencies?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>V1.1 Statistics producers should maintain and refresh their
  understanding of the use and potential use of the statistics and data. They
  should consider the ways in which the statistics might be used and the nature
  of the decisions that are or could be informed by them.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6519059 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q42</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>All or part of the analysis is reliant on a single person?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>V4 Statistics producers should be creative and motivated to
  improve statistics and data, recognising the potential to harness
  technological advances for the development of all parts of the production and
  dissemination process. T4.3 Sufficient human, financial and technological
  resources should be provided to deliver statistical services that serve the
  public good.</td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6519059 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q43</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is it clear why important decisions were made and who made them?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q2 Producers of statistics and data should use the best
  available methods and recognised standards, and be open about their
  decisions.</td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl6519059 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q44</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>If changes need to be made to any code or datasets, is it
  difficult to track who made these changes and why those changes were
  made?<span style='mso-spacerun:yes'> </span></td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>V4 Statistics producers should be creative and motivated to
  improve statistics and data, recognising the potential to harness
  technological advances for the development of all parts of the production and
  dissemination process.</td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6519059 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q45</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>Would another analyst be able to reproduce your model output or
  continue the work (without talking to you first)?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>V5 Statistics and data should be published in forms that enable
  their reuse. Producers should use existing data wherever possible and only
  ask for more where justified.</td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl6519059 width=31 style='height:100.0pt;border-top:
  none;width:24pt'>Q46</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>Do you use internal peer review to check scripts and code,
  documentation, implementation of methods, processes and outputs?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q3 Producers of statistics and data should explain clearly how
  they assure themselves that statistics and data are accurate, reliable,
  coherent and timely. T4.6 Independent measures, such as internal and external
  audit, peer review and National Statistics Quality Reviews, should be used to
  evaluate the effectiveness of statistical processes. Statistics producers
  should be open about identified areas for improvement.</td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl6519059 width=31 style='height:100.0pt;border-top:
  none;width:24pt'>Q47</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is your code and analysis ever peer reviewed by someone outside
  your team or organisation?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q3 Producers of statistics and data should explain clearly how
  they assure themselves that statistics and data are accurate, reliable,
  coherent and timely. T4.6 Independent measures, such as internal and external
  audit, peer review and National Statistics Quality Reviews, should be used to
  evaluate the effectiveness of statistical processes. Statistics producers
  should be open about identified areas for improvement.</td>
 </tr>
 <tr height=167 style='height:125.0pt'>
  <td height=167 class=xl6519059 width=31 style='height:125.0pt;border-top:
  none;width:24pt'>Q48</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>What is the assessment of the quality of your analytical
  outputs?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q3 Producers of statistics and data should explain clearly how
  they assure themselves that statistics and data are accurate, reliable,
  coherent and timely. Q3.2 Quality assurance arrangements should be
  proportionate to the nature of the quality issues and the importance of the
  statistics in serving the public good. Statistics producers should be
  transparent about the quality assurance approach taken throughout the
  preparation of the statistics. The risk and impact of quality issues on
  statistics and data should be minimised to an acceptable level for the
  intended uses.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=167 style='height:125.0pt'>
  <td height=167 class=xl6519059 width=31 style='height:125.0pt;border-top:
  none;width:24pt'>Q49</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>How do you assure yourselves that analysis carried out is
  correct?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q3 Producers of statistics and data should explain clearly how
  they assure themselves that statistics and data are accurate, reliable,
  coherent and timely.Q3.2 Quality assurance arrangements should be
  proportionate to the nature of the quality issues and the importance of the
  statistics in serving the public good. Statistics producers should be
  transparent about the quality assurance approach taken throughout the
  preparation of the statistics. The risk and impact of quality issues on
  statistics and data should be minimised to an acceptable level for the
  intended uses.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6519059 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q50</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>Do the outputs of your analysis match reported content?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q3 Producers of statistics and data should explain clearly how
  they assure themselves that statistics and data are accurate, reliable,
  coherent and timely.</td>
 </tr>
 <tr height=150 style='height:112.5pt'>
  <td height=150 class=xl6519059 width=31 style='height:112.5pt;border-top:
  none;width:24pt'>Q51</td>
  <td class=xl6519059 width=321 style='border-top:none;border-left:none;
  width:241pt'>If you find outliers or unusual trends in the data, what steps
  are taken to investigate them?</td>
  <td class=xl6519059 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q3 Producers of statistics and data should explain clearly how
  they assure themselves that statistics and data are accurate, reliable,
  coherent and timely. Q3.3 The quality of the statistics and data, including
  their accuracy and reliability, coherence and comparability, and timeliness
  and punctuality, should be monitored and reported regularly. Statistics
  should be validated through comparison with other relevant statistics and
  data sources. The extent and nature of any uncertainty in the estimates should
  be clearly explained.</td>
  </tr>
</table>

## Aqua Roles and Responsibilities

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
<TR VALIGN=TOP>
    <th> </th>
    <th> Questions</th>
    <th> Who is responsible for answering this in light of AQUA book?</th>
    <th> Which AQUA book responsibilities have a role?</th>

</tr>
 <tr height=83 style='height:62.5pt'>

 <td height=83 class=xl6530071 width=31 style='height:62.5pt;width:24pt'>Q26</td>
  <td class=xl6530071 width=321 style='border-left:none;width:241pt'>How the
  data used in the analysis will be processed prior to and during use?</td>
  <td class=xl6530071 width=182 style='border-left:none;width:137pt'>Analyst,
  analytical assurer</td>
  <td class=xl6530071 width=299 style='border-left:none;width:225pt'>Analyst
  should collect and manage data. Understand data accuracy and uncertainties.
  Capture, manage and understand implicit assumptions made. Analytical assurer
  should be involved.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl6530071 width=31 style='height:100.0pt;border-top:
  none;width:24pt'>Q27</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is the data appropriate given the methods selected?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, analytical assurer, commissioner</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analyst should understand data accuracy and uncertainties and
  capture, manage and understand implicit assumptions made. Analyst should
  engage appropriate subject matter experts, at the appropriate time, when
  collecting data. NB: The commissioner may be a subject matter expert.
  Analytical assurer should also be involved.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6530071 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q28</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>What are the strengths and limitations of the data that you
  use?<span style='mso-spacerun:yes'> </span></td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, analytical assurer</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>If applicable, analyst should undertake parametric analysis to
  understand the consequences of missing or uncertain data and assumptions.
  Analytical assurer should be involved.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6530071 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q29</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is there a robust relationship between your team and data
  providers? Does your data provider have a good understanding of how and why
  you are using their data?<br>
    Do you have a good understanding of how the data provider collects,
  processes and quality assures the data?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, analytical assurer</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>The analytical assurer should expect to review evidence that
  there has been sufficient networking between analysts as the providers of
  data and other evidence sources.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6530071 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q30</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is there a formal agreement in place that specifies when, what
  and how the data will be received? If not, do you think this would be
  helpful?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner, analyst, analytical assurer</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>Commissioner may need to provide the analyst with agreement to
  the use of specific data. Analyst should ensure data formats, units, and
  context are properly understood and handled. Analytical assurer should be
  involved.</td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl6530071 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q31</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>Do you know what quality checks are carried out on the data
  before you receive them?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analyst should understand data accuracy and uncertainties and
  capture, manage and understand implicit assumptions made. Analytical assurer
  should also be involved.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=201 style='height:151.0pt'>
  <td height=201 class=xl6530071 width=31 style='height:151.0pt;border-top:
  none;width:24pt'>Q32</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>How will you work with your data provider when your data
  requirements change?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner, analyst, analytical assurer</td>
  <td class=xl6930071 width=299 style='border-top:none;border-left:none;
  width:225pt'>During the design and conduct of analysis phases, the
  commissioner may need to provide the analyst with important information for
  the analysis to proceed or be asked for other essential input, i.e.,
  agreement to the use of specific data and assumptions and provide agreement
  and sign-off to any assumptions that are developed as part of the project.
  Analyst should understand data accuracy and uncertainties and capture, manage
  and understand implicit assumptions made. Analytical assurer should also be
  involved.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=201 style='height:151.0pt'>
  <td height=201 class=xl6530071 width=31 style='height:151.0pt;border-top:
  none;width:24pt'>Q33</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>How do you know if your data provider makes a change to their
  systems or processes, which could impact the data you receive and/or the
  statistics you produce?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner, analyst, analytical assurer</td>
  <td class=xl6930071 width=299 style='border-top:none;border-left:none;
  width:225pt'>During the design and conduct of analysis phases, the
  commissioner may need to provide the analyst with important information for
  the analysis to proceed or be asked for other essential input, i.e.,
  agreement to the use of specific data and assumptions and provide agreement
  and sign-off to any assumptions that are developed as part of the project.
  Analyst should understand data accuracy and uncertainties and capture, manage
  and understand implicit assumptions made. Analytical assurer should also be
  involved.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6530071 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q34</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>How did you choose the methods for the analysis? How do you know
  the method you are using is appropriate?<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, analytical assurer</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>During the design phase, the analyst will convert the commission
  into an analytical plan and will consider the inputs, possible analytical
  methods, and the expected outputs that will be produced. The analytical
  assurer should at this stage check that the proposed design meets the
  commissioner’s requirements.</td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl6530071 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q35</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>Are reasonable alternative methods have been explored and
  rejected for good reasons?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst</td>
  <td class=xl6730071 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analyst should review the structure of the analysis as a whole
  and consider carefully whether there are any other ways in which it could
  have been approached.</td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6530071 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q36</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>How do you know that your analysis or statistical process is
  working correctly?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analyst should validate that the analysis requested is actually
  what the commissioner requires in order to answer the problem.<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl6530071 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q37</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>Can you describe the assumptions of your analysis, when they
  were made and who made them and signed them off?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, analytical assurer</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analyst should capture, manage and understand implicit
  assumptions made. Analytical assurer should be involved.<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6530071 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q38</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>How the assumptions are validated and assured prior to use?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, analytical assurer</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>If applicable, analyst should undertake parametric analysis to
  understand the consequences of missing or uncertain assumptions, Analytical
  assurer should be involved.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl6530071 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q39</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>How do you measure and report uncertainty in your analysis?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, commissioner</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analyst should determine and communicate the uncertainty
  associated with the outputs of their analysis so that the commissioner can
  make informed decisions. The range of possible outcomes and their relative
  likelihoods should be described.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl6530071 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q40</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>Have you considered the implications of any unquantified
  uncertainties?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, commissioner</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>If the uncertainties are too complex for analysts to quantify,
  even approximately, the analysts should say so in order that the commissioner
  can take this into account.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl6530071 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q41</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>Can you explain the impact of your work/output on downstream
  processes? Are there any risks around these dependencies?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, analytical assurer</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analyst should ensure implications of any data dependencies or
  relationships to other analysis or methods are understood. Analytical assurer
  should be involved.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6530071 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q42</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>All or part of the analysis is reliant on a single person?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analytical assurer, analyst, commissioner</td>
  <td class=xl6730071 width=299 style='border-top:none;border-left:none;
  width:225pt'>All analysis requires some checks, at some level, by another
  competent person wherever and whenever practicable. Comissioner, analyst and
  analytical assurer are all expected to be involved in each stage of
  analytical cycle.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6530071 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q43</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is it clear why important decisions were made and who made them?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analytical assurer, analyst</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analytical assurer should ensure that a suitable audit trail is
  in place that clarifies the level of validation, scope, and risks associated
  with the analysis. Best practice includes the production of validation log
  books. Analyst should be involved.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=150 style='height:112.5pt'>
  <td height=150 class=xl6530071 width=31 style='height:112.5pt;border-top:
  none;width:24pt'>Q44</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>If changes need to be made to any code or datasets, is it
  difficult to track who made these changes and why those changes were
  made?<span style='mso-spacerun:yes'> </span></td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analytical assurer, analyst</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>To facilitate analytical audit, an appropriate version control
  systemshould be established for both the analysis as a whole and for the
  supporting data and assumptions. Analytical assurer should ensure a suitable
  audit trail is in place that clarifies the level of validation, scope, and
  risks associated with the analysis. Best practice includes the production of
  validation log books. Analyst should be involved.<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6530071 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q45</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>Would another analyst be able to reproduce your model output or
  continue the work (without talking to you first)?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, analytical assurer</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>Quality analysis needs to be repeatable. Analyst should check
  that the entire analytical process reflects the principles of RIGOUR
  (Repeatable, Independent, Grounded in reality, Objective,
  Uncertainty-managed, Robust)</td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl6530071 width=31 style='height:100.0pt;border-top:
  none;width:24pt'>Q46</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>Do you use internal peer review to check scripts and code,
  documentation, implementation of methods, processes and outputs?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>In addition to conducting the analysis, the analyst should also
  provide proportionate documentation that outlines the verification and
  validation activities that their analysis has been subjected to. When the
  analyst is conducting their analysis, they will be performing their own tests
  to check their analysis and they will commission other verification and
  validation activities as required.</td>
 </tr>
 <tr height=233 style='height:175.0pt'>
  <td height=233 class=xl6530071 width=31 style='height:175.0pt;border-top:
  none;width:24pt'>Q47</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is your code and analysis ever peer reviewed by someone outside
  your team or organisation?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, analytical assurer</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>The people responsible for delivering the analysis frequently
  assist the commissioner in structuring the question in order to ensure the
  appropriate analysis is performed. Some analysis may require external
  specialists and therefore analysts may also have responsibilities as part of
  the procurement process. Analysts, including those 3rd parties providing
  analysis, should also provide proportionate documentation that outlines the
  verification and validation activities undertaken and the associated conclusion.
  The analytical assurer is responsible for advising the commissioner on
  whether appropriate analytical quality assurance has taken place.<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl6530071 width=31 style='height:100.0pt;border-top:
  none;width:24pt'>Q48</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>What is the assessment of the quality of your analytical
  outputs?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner, analytical assurer</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>As part of the delivery phase, the commissioner should ensure
  that there is an assessment of the level of analytical quality assurance of
  the analysis, making note of where there has been a trade-off between time,
  resources and quality. The analytical assurer is responsible for advising the
  commissioner on whether appropriate analytical quality assurance has taken
  place.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=200 style='height:150.0pt'>
  <td height=200 class=xl6530071 width=31 style='height:150.0pt;border-top:
  none;width:24pt'>Q49</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>How do you assure yourselves that analysis carried out is
  correct?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner, analyst, analytical assurer</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analyst testing covers those activities where the analyst builds
  in checks and processes to ensure that their analysis is correct. During the
  delivery phase, the commissioner has additional important roles, both in
  providing feedback to assist in the correct interpretation of the results and
  to determine whether the analysis has addressed their commission. When
  analyst are conducting their analysis, the analytical assurer can then
  comment on whether the analysis is still meeting the needs of the commission
  to ensure best use of the results</td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl6530071 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q50</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>Do the outputs of your analysis match reported content?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner, analyst</td>
  <td class=xl6530071 width=299 style='border-top:none;border-left:none;
  width:225pt'>When interpreting the results of a piece of analysis, the
  commissioner provides constructive challenge and, with the analyst, explores
  whether further analysis is required.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6530071 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q51</td>
  <td class=xl6530071 width=321 style='border-top:none;border-left:none;
  width:241pt'>If you find outliers or unusual trends in the data, what steps
  are taken to investigate them?</td>
  <td class=xl6530071 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, analytical assurer</td>
  <td class=xl6730071 width=299 style='border-top:none;border-left:none;
  width:225pt'>If applicable, analyst should undertake parametric analysis to
  understand the consequences of missing or uncertain data and assumptions.
  Analytical assurer should be involved.<span style='mso-spacerun:yes'> </span></td>
  </tr>
</table>

:::

## IV. Delivery

::: {.panel-tabset}

## Quality Questions


<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<table style="width:100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse; font size="2" face="Courier New">
<TR VALIGN=TOP>
    <th> </th>
    <th style="width:50%; text-align: center;"> Questions</th>
    <th style="width:50%; text-align: center;">Answers</th>
    <th style="text-align: center"> Answer added by</th>
    <th style="text-align: center"> Date answer added</th>
    <th style="text-align: center"> Is SRO satisfied with the answer?</th>
    <th style="text-align: center"> Next review due on</th>
    <th style="text-align: center"> Has anything changed from last review?</th>



</tr>
 <tr height=83 style='height:62.5pt'>
<td height=21 class=xl657005 width=31 style='height:15.5pt;width:24pt'>Q52</td>
  <td class=xl657005 width=321 style='border-left:none;width:241pt'>Could you give a clear account of what can and cannot be inferred from your final output?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl657005 width=31 style='height:15.5pt;border-top:none;
  width:24pt'>Q53</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Have you assessed the impact of the data and model limitations and set out how they will affect the quality and use of the outputs?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q54</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	Have you sense checked outputs with user groups and stakeholders?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl657005 width=31 style='height:15.5pt;border-top:none;
  width:24pt'>Q55</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'> Is uncertainty related to data quality, assumptions and methodology clearly communicated to users?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl657005 width=31 style='height:15.5pt;border-top:none;
  width:24pt'>Q56</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'> Are the implications of unquantified uncertainties communicated to users?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q57</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	Is model documentation including technical guide publicly available?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q58</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>	Does the technical guide explains how to use the model to obtain valid outputs?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q59</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Have you fully documented the model code?</td>

  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl657005 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q60</td>
  <td class=xl657005 width=321 style='border-top:none;border-left:none;
  width:241pt'>Are users able to feed back on the suitability of outputs?</td>
  
  <td> <p id="content" contenteditable>Enter your answer here...                         </p></td>
  <td> <p id="content" contenteditable> Enter full name</p></td>
  <td> <p id="content" contenteditable> Enter date </p></td>
  <td> <p id="content" contenteditable> Yes/No </p></td>
  <td> <p id="content" contenteditable> Enter next review date </p></td>
  <td> <p id="content" contenteditable> Enter text </p></td>

  </tr>
</table>


## Importance 

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
<TR VALIGN=TOP>
    <th> </th>
    <th> Questions</th>
    <th> Why do I need to know the answer to this?</th>

</tr>
 <tr height=83 style='height:62.5pt'>

<td height=183 class=xl665210 width=31 style='height:137.5pt;width:24pt'>Q52</td>
  <td class=xl665210 width=319 style='border-left:none;width:240pt'>Could you
  give a clear account of what can and cannot be inferred from your final
  output?</td>
  <td class=xl665210 width=396 style='border-left:none;width:297pt'>Often the
  aim of final output (be in the form of data tables, graphs, regression
  results or commentary around any of them) is to inform decison-making. The
  final output may represent predictions, involving lots of underlying
  assumptions. There is a risk that the primary or secondary users may
  misinterpret the findings, make wrong comparisons, use it for unsuitable
  purposes and arrive to wrong conclusions. For example, a non-expert user may
  wrongly interpret correlation as causation or use incomplete or disconnected
  data for forecast. It is, therefore, important to clearly inform and remind
  the users about the correct use of the output and what can and connot be
  inferred from it.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl665210 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q53</td>
  <td class=xl675210 width=319 style='border-top:none;border-left:none;
  width:240pt'>Have you assessed the impact of the data and model limitations
  and set out how they will affect the quality and use of the outputs?</td>
  <td class=xl665210 width=396 style='border-top:none;border-left:none;
  width:297pt'>It is important to describe why each limitation related to data
  and methods exist, why it cannot be overcome using the chosen approach and
  what impact does it have on the quality and interpretation of the output
  produced. Results are of very little value if limitations aren't documented
  and the rationale for them explained.</td>
 </tr>
 <tr height=33 style='height:25.0pt'>
  <td height=33 class=xl665210 width=31 style='height:25.0pt;border-top:none;
  width:24pt'>Q54</td>
  <td class=xl665210 width=319 style='border-top:none;border-left:none;
  width:240pt'>Have you sense checked outputs with user groups and
  stakeholders?</td>
  <td class=xl665210 width=396 style='border-top:none;border-left:none;
  width:297pt'>The credibility of outputs should be checked by experts/relevant
  stakeholders/users and sense checked to ensure they are useful.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl665210 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q55</td>
  <td class=xl665210 width=319 style='border-top:none;border-left:none;
  width:240pt'>Is uncertainty related to data quality, assumptions and
  methodology clearly communicated to users?</td>
  <td class=xl665210 width=396 style='border-top:none;border-left:none;
  width:297pt'>Outputs will never be 100% accurate. Users will need to
  understand how uncertainties related to data, assumptions and methodology
  feed into and through the analysis workflow and what this means for the use
  of the outputs. Results must clearly set out how uncertainty affects the
  findings from the analysis, or else we risk misinterpretations and
  conclusions being overly reliant on imprecise results.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl665210 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q56</td>
  <td class=xl665210 width=319 style='border-top:none;border-left:none;
  width:240pt'>Are the implications of unquantified uncertainties communicated
  to users?</td>
  <td class=xl665210 width=396 style='border-top:none;border-left:none;
  width:297pt'>Users should be provided with a sound understanding of important
  uncertainties which have not been captured in the analysis. Where possible,
  your team should make reasonable judgements about the likely size and
  direction of the unquantified uncertainty and provide a qualitative
  description informing users about why they can't be quantified and what might
  be their likely impact.</td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl665210 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q57</td>
  <td class=xl665210 width=319 style='border-top:none;border-left:none;
  width:240pt'>Is model documentation including technical guide publicly
  available?</td>
  <td class=xl665210 width=396 style='border-top:none;border-left:none;
  width:297pt'>Transparency about your analysis would enable proper scrutiny
  and challenge, promotes public trust and encourages re-use of the resources
  you develop.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl665210 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q58</td>
  <td class=xl665210 width=319 style='border-top:none;border-left:none;
  width:240pt'>Does the technical guide explains how to use the model to obtain
  valid outputs?</td>
  <td class=xl665210 width=396 style='border-top:none;border-left:none;
  width:297pt'>Technical guide helps in understanding the analysis better and
  in getting familiar with it in less time. A well-written technical guide is
  esstential to maintain the analysis over the project cycle. It helps both the
  primary and secondary users of the analysis in replicating it, finding
  answers to their questions on methodology and in building their trust in the
  final output.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl665210 width=31 style='height:62.5pt;border-top:none;
  width:24pt'>Q59</td>
  <td class=xl665210 width=319 style='border-top:none;border-left:none;
  width:240pt'>Have you fully documented the model code?</td>
  <td class=xl665210 width=396 style='border-top:none;border-left:none;
  width:297pt'>Technical guide can only serve its purpose if the model code is
  fully documented within it. Model code should be documented in a coherent
  manner for any new user of the model to understand and execute it as easily
  and quickly as possible. Code should follow best practice guidance.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl665210 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q60</td>
  <td class=xl665210 width=319 style='border-top:none;border-left:none;
  width:240pt'>Are users able to feed back on the suitability of outputs?</td>
  <td class=xl665210 width=396 style='border-top:none;border-left:none;
  width:297pt'>The more external critique exists within an analysis the better.
  Users in particular need to be able to feedback to your team to ensure that
  the results are meeting their needs. User feedback and customer reviews not
  only act to inform the team of the changes required but also act as evidence
  that users have been consulted.<span style='mso-spacerun:yes'> </span></td>

  </tr>
</table>


## Code of Practice for Statistics

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
<TR VALIGN=TOP>
    <th> </th>
    <th> Questions</th>
    <th> Which pillar and principle of Code of Practice are relevant here?  
    *Trustworthiness (T), Quality (Q), Value (V)</th>

</tr>
 <tr height=83 style='height:62.5pt'>

<td height=83 class=xl655210 width=31 style='height:62.5pt;width:24pt'>Q52</td>
  <td class=xl655210 width=321 style='border-left:none;width:241pt'>Could you
  give a clear account of what can and cannot be inferred from your final
  output?</td>
  <td class=xl655210 width=368 style='border-left:none;width:276pt'>Q2.4
  Relevant limitations arising from the methods and their application,
  including bias and uncertainty, should be identified and explained to users.
  An indication of their likely scale and the steps taken to reduce their
  impact on the statistics should be included in the explanation.</td>
 </tr>
 <tr height=167 style='height:125.0pt'>
  <td height=167 class=xl655210 width=31 style='height:125.0pt;border-top:none;
  width:24pt'>Q53</td>
  <td class=xl655210 width=321 style='border-top:none;border-left:none;
  width:241pt'>Have you assessed the impact of the data and model limitations
  and set out how they will affect the quality and use of the outputs?</td>
  <td class=xl655210 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q3 Producers of statistics and data should explain clearly how
  they assure themselves that statistics and data are accurate, reliable,
  coherent and timely. Q1.5 Potential bias, uncertainty and possible distortive
  effects in the source data should be identified and the extent of any impact
  on the statistics should be clearly reported. Q3.1 Statistics should be
  produced to a level of quality that meets users’ needs. The strengths and
  limitations of the statistics and data should be considered in relation to
  different uses, and clearly explained alongside the statistics.</td>
 </tr>
 <tr height=50 style='height:37.5pt'>
  <td height=50 class=xl655210 width=31 style='height:37.5pt;border-top:none;
  width:24pt'>Q54</td>
  <td class=xl655210 width=321 style='border-top:none;border-left:none;
  width:241pt'>Have you sense checked outputs with user groups and
  stakeholders?</td>
  <td class=xl655210 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q3 Producers of statistics and data should explain clearly how
  they assure themselves that statistics and data are accurate, reliable,
  coherent and timely.</td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl655210 width=31 style='height:100.0pt;border-top:none;
  width:24pt'>Q55</td>
  <td class=xl655210 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is uncertainty related to data quality, assumptions and
  methodology clearly communicated to users?</td>
  <td class=xl655210 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q1.5 Potential bias, uncertainty and possible distortive effects
  in the source data should be identified and the extent of any impact on the
  statistics should be clearly reported. Q2.4 Relevant limitations arising from
  the methods and their application, including bias and uncertainty, should be
  identified and explained to users. An indication of their likely scale and
  the steps taken to reduce their impact on the statistics should be included
  in the explanation.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl655210 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q56</td>
  <td class=xl655210 width=321 style='border-top:none;border-left:none;
  width:241pt'>Are the implications of unquantified uncertainties communicated
  to users?</td>
  <td class=xl655210 width=368 style='border-top:none;border-left:none;
  width:276pt'>Q2.4 Relevant limitations arising from the methods and their
  application, including bias and uncertainty, should be identified and
  explained to users. An indication of their likely scale and the steps taken
  to reduce their impact on the statistics should be included in the
  explanation. Q3.3 The extent and nature of any uncertainty in the estimates
  should be clearly explained.</td>
 </tr>
 <tr height=67 style='height:50.0pt'>
  <td height=67 class=xl655210 width=31 style='height:50.0pt;border-top:none;
  width:24pt'>Q57</td>
  <td class=xl655210 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is model documentation including technical guide publicly
  available?</td>
  <td class=xl655210 width=368 style='border-top:none;border-left:none;
  width:276pt'>V2 Statistics and data should be equally available to all, not
  given to some people before others. They should be published at a sufficient
  level of detail and remain publicly available.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl655210 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q58</td>
  <td class=xl655210 width=321 style='border-top:none;border-left:none;
  width:241pt'>Does the technical guide explains how to use the model to obtain
  valid outputs?</td>
  <td class=xl655210 width=368 style='border-top:none;border-left:none;
  width:276pt'>V2 Statistics and data should be equally available to all, not
  given to some people before others. They should be published at a sufficient
  level of detail and remain publicly available. V3 Statistics and data should
  be presented<span style='mso-spacerun:yes'>  </span>clearly, explained
  meaningfully and provide authoritative insights that serve the public good.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl655210 width=31 style='height:87.5pt;border-top:none;
  width:24pt'>Q59</td>
  <td class=xl655210 width=321 style='border-top:none;border-left:none;
  width:241pt'>Have you fully documented the model code?</td>
  <td class=xl675210 width=368 style='border-top:none;border-left:none;
  width:276pt'>T4.4 Good business practices should be maintained in the use of
  resources. Where appropriate, statistics producers should take opportunities
  to share resources and collaborate to achieve common goals and produce
  coherent statistics. Q2.1 Methods and processes should be based on national
  or international good practice, scientific principles, or established
  professional consensus.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=333 style='height:250.0pt'>
  <td height=333 class=xl655210 width=31 style='height:250.0pt;border-top:none;
  width:24pt'>Q60</td>
  <td class=xl655210 width=321 style='border-top:none;border-left:none;
  width:241pt'>Are users able to feed back on the suitability of outputs?</td>
  <td class=xl675210 width=368 style='border-top:none;border-left:none;
  width:276pt'>V1 Users of statistics and data should be at the centre of
  statistical production; their needs should be understood, their views sought
  and acted upon, and their use of statistics supported. V1.4 Statistics
  producers should engage publicly through a variety of means that are
  appropriate to the needs of different audiences and proportionate to the
  potential of the statistics to serve the public good. An open dialogue should
  be maintained using proactive formal and informal engagement to listen to the
  views of new and established contacts. Statistics producers should undertake
  public engagement collaboratively wherever possible, working in partnership
  with policy makers and other statistics producers to obtain the views of
  stakeholders. V1.5 The views received from users, potential users and other
  stakeholders should be addressed, where practicable. Statistics producers
  should consider whether to produce new statistics to meet identified
  information gaps. Feedback should be provided to them about how their needs
  can and cannot be met, being transparent about reasons for the decisions made and any constraints.</td>
 </tr>
  </tr>
</table>

## Aqua Roles and Responsibilities


<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
<TR VALIGN=TOP>
    <th> </th>
    <th> Questions</th>
    <th> Who is responsible for answering this in light of AQUA book?</th>
    <th> Which AQUA book responsibilities have a role?</th>

</tr>
 <tr height=83 style='height:62.5pt'>

<td height=67 class=xl6531542 width=31 style='height:50.0pt;width:24pt'>Q52</td>
  <td class=xl6531542 width=321 style='border-left:none;width:241pt'>Could you
  give a clear account of what can and cannot be inferred from your final
  output?</td>
  <td class=xl6531542 width=182 style='border-left:none;width:137pt'>Commissioner</td>
  <td class=xl6531542 width=299 style='border-left:none;width:225pt'>During the
  delivery phase, the commissioner has another important role when they receive
  the interpretation of the results and determine whether it has addressed
  their request.</td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl6531542 width=31 style='height:100.0pt;border-top:
  none;width:24pt'>Q53</td>
  <td class=xl6531542 width=321 style='border-top:none;border-left:none;
  width:241pt'>Have you assessed the impact of the data and model limitations
  and set out how they will affect the quality and use of the outputs?</td>
  <td class=xl6531542 width=182 style='border-top:none;border-left:none;
  width:137pt'>Commissioner, analytical assurer</td>
  <td class=xl6531542 width=299 style='border-top:none;border-left:none;
  width:225pt'>The commissioner must be confident in the quality of the outputs
  and understand the strengths, limitations and contexts of the analysis so
  that the results are correctly interpreted. The analytical assurer sign-off
  provides confidence that analysis risks, limitations and major assumptions
  are understood by the users of the analysis<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=217 style='height:162.5pt'>
  <td height=217 class=xl6531542 width=31 style='height:162.5pt;border-top:
  none;width:24pt'>Q54</td>
  <td class=xl6531542 width=321 style='border-top:none;border-left:none;
  width:241pt'>Have you sense checked outputs with user groups and
  stakeholders?</td>
  <td class=xl6531542 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, analytical assurer</td>
  <td class=xl6731542 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analyst and analytical assurere should assist peer review
  checks. Peer reviews may use internal or external parties to provide critical
  challenge of the analysis. The views of others – whether in an expert
  capacity or not – can provide constructive challenge to the analytical
  approach, application of a methodology or interpretation of the analysis.
  Verification checks may be performed by an analyst who has had no involvement
  in the <br>
    design and execution of the analysis in order to ensure that a fresh pair
  of eyes considers the analysis and the adopted approach</td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl6531542 width=31 style='height:100.0pt;border-top:
  none;width:24pt'>Q55</td>
  <td class=xl6531542 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is uncertainty related to data quality, assumptions and
  methodology clearly communicated to users?</td>
  <td class=xl6531542 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst</td>
  <td class=xl6531542 width=299 style='border-top:none;border-left:none;
  width:225pt'>The analyst should determine and communicate the uncertainty
  associated with the outputs of their analysis so that the commissioner can
  make informed decisions. As part of the delivery phase, the commissioner
  should ensure that an assessment of uncertainty has been provided and that
  the implications of the uncertainties are understood<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=150 style='height:112.5pt'>
  <td height=150 class=xl6531542 width=31 style='height:112.5pt;border-top:
  none;width:24pt'>Q56</td>
  <td class=xl6531542 width=321 style='border-top:none;border-left:none;
  width:241pt'>Are the implications of unquantified uncertainties communicated
  to users?</td>
  <td class=xl6531542 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, commissioner</td>
  <td class=xl6531542 width=299 style='border-top:none;border-left:none;
  width:225pt'>If the uncertainties are too complex for analysts to quantify,
  even approximately, the analysts should say so in order that the commissioner
  can take this into account. While communicating the results of analysis to
  decision-makers or other stakeholders, commissioner should be open about the
  existence of any deep uncertainties whose impact cannot be assessed, and
  explain how they are managing those uncertainties.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl6531542 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q57</td>
  <td class=xl6531542 width=321 style='border-top:none;border-left:none;
  width:241pt'>Is model documentation including technical guide publicly
  available?</td>
  <td class=xl6531542 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, analytical assurer</td>
  <td class=xl6731542 width=299 style='border-top:none;border-left:none;
  width:225pt'>Produce appropriate design documentation. Best practice includes
  maintaining a record of the work that has been done in a technical report,
  including a concept of analysis, user requirements, design specification,
  functional specification, data dictionary, and test plan.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl6531542 width=31 style='height:75.0pt;border-top:none;
  width:24pt'>Q58</td>
  <td class=xl6531542 width=321 style='border-top:none;border-left:none;
  width:241pt'>Does the technical guide explains how to use the model to obtain
  valid outputs?</td>
  <td class=xl6531542 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, analytical assurer</td>
  <td class=xl6731542 width=299 style='border-top:none;border-left:none;
  width:225pt'>Produce appropriate design documentation. Best practice includes
  maintaining a record of the work that has been done in a technical report,
  including a concept of analysis, user requirements, design specification,
  functional specification, data dictionary, and test plan.</td>
 </tr>
 <tr height=168 style='height:126.0pt'>
  <td height=168 class=xl6531542 width=31 style='height:126.0pt;border-top:
  none;width:24pt'>Q59</td>
  <td class=xl6531542 width=321 style='border-top:none;border-left:none;
  width:241pt'>Have you fully documented the model code?</td>
  <td class=xl6531542 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst, analytical assurer</td>
  <td class=xl6931542 width=299 style='border-top:none;border-left:none;
  width:225pt'>Analyst should produce appropriate design and technical
  documentation. Best practice can include a concept of analysis, user
  requirements, design specification, functional specification, data
  dictionary, and test plan. all analysis should have documentation for the
  user, even if that is just the analyst leading the analysis. This is to
  ensure that they have captured sufficient material to assist them if the
  analysis is revisited in due course. Analytical assurer should be involved.</td>
 </tr>
 <tr height=167 style='height:125.0pt'>
  <td height=167 class=xl6531542 width=31 style='height:125.0pt;border-top:
  none;width:24pt'>Q60</td>
  <td class=xl6531542 width=321 style='border-top:none;border-left:none;
  width:241pt'>Are users able to feed back on the suitability of outputs?</td>
  <td class=xl6531542 width=182 style='border-top:none;border-left:none;
  width:137pt'>Analyst</td>
  <td class=xl6731542 width=299 style='border-top:none;border-left:none;
  width:225pt'>The utility of the analytical output can be assessed through
  gathering feedback from the end users about its practical benefits. Quality
  analysis should be free of prejudice or bias. In doing so, care should be
  taken to appropriately balance the views across all stakeholders and experts.
  Analyst should check that the entire analytical process reflects the
  principles of RIGOUR (Repeatable, Independent, Grounded in reality,
  Objective, Uncertainty-managed, Robust)</td>
  </tr>
</table>


:::

